### ISSUE TITLE
Multi-line prompts are repeated when the terminal window is resized. (repeat of #321)

### ISSUE THREAD

**Issue by joesanford** [fish-shell/fish-shell#2320]
This bug is still occurring with both multi-line and single-line prompts.

**Comment by faho** [comment]
Could you add some more information? Which OS, which terminal, which fish version? What's your prompt? Any custom functions, especially signal handlers for SIGWINCH?

I cannot reproduce this on archlinux with konsole, fish 2.2.0-188-g3f43050, the classic+git prompt, a custom right-prompt and no custom SIGWINCH handlers.

**Comment by faho** [comment]
Also no issue with the example in #321 - `printf '1\n2\n$'.

**Comment by joesanford** [comment]
Mac OS X 10.10.5. Was able to replicate with both iTerm2 and Terminal. fish 2.2.0. Prompts that have shown this are Pythonista and bira.

**Comment by Determinant** [comment]
Same issue here. It does not seem related to the OS X version, I tried on both 10.10.5 and 10.11. It occurs when resizing window of the terminal.

**Comment by faho** [comment]
@Determinant, @joesanford: Can you try with current git master? It's possible this was already fixed since 2.2.0.

**Comment by Determinant** [comment]
Sorry, but I'm using 2.2.0. The problem still exists.

On Saturday, October 31, 2015, Fabian Homborg <notifications@github.com>
wrote:

> @Determinant <https://github.com/Determinant>, @joesanford
> <https://github.com/joesanford>: Can you try with current git master?
> It's possible this was already fixed since 2.2.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fish-shell/fish-shell/issues/2320#issuecomment-152593451>
> .
>


-- 
--- This information is automatically generated ---
Welcome to My Blog : http://tedyin.com

ted.sybil aka. ymfoi aka. Ted Yin

**Comment by faho** [comment]
We know that you have this problem with 2.2.0, but what about newer versions?

**Comment by ridiculousfish** [comment]
I can reproduce on master.

The resizing stuff is rather tricky, but zsh seems to do much better here. I think what's going on is that we're soft-wrapping from the previous line, and need to have a hard return there.

**Comment by tylerhjones** [comment]
Is anyone else still receiving this problem?

**Comment by faho** [comment]
I still can't reproduce - newest fish, newest konsole on archlinux.

**Comment by ixjlyons** [comment]
I'm not sure about Github notifications when an issue is referenced from another, but I wanted to point out the duplicate issue I filed #2816 (sorry for the dup -- I searched but didn't see this one). I'm able to replicate this issue with all terminal emulators based on recent (gtk3) versions of vte.

I filed a bug report against vte [here](https://bugzilla.gnome.org/show_bug.cgi?id=763390), and one of the developers seemed to figure out what the problem was. See comment 4 specifically.

I'd love to contribute to fish, and I have some C++ knowledge, but I'm still learning the basics of how shells work. I implemented the vte dev's suggestion [here](https://github.com/ixjlyons/fish-shell/commit/0fecba9bedbc219c35a2175d0a69ed2fa502587a), but I have no idea whether or not this will cause side effects. Tests seem to pass, and I'm using it as my daily driver without issue so far.

**Comment by joesanford** [comment]
The problem still exists with 2.2.0 on Mac OS X 10.10 with iTerm2. Multiple users where I work can confirm as well with the same setup

**Comment by faho** [comment]
@joesanford: Can you try erasing `__fish_winch_handler`? Unfortunately this means you'd need to run `functions -e __fish_winch_handler` interactively as it is defined only after the first prompt event (in `__fish_config_interactive.fish`), but it should do for a simple test.

The idea is that these terminals (iTerm2 and newer VTE) will reflow text themselves, so fish doing it just gets in the way. Or maybe their reflow doesn't work for our needs, let's see.

**Comment by zanchey** [comment]
Sounds like we should try the patch suggested by the VTE developers.

**Comment by Eyenseo** [comment]
As reference for PR #3194 

To reproduce the bug the prompt has to span over multiple lines. If the terminal is then resized the prompt will be partially overwritten (see @joesanford image).

My terminal is [Termite](https://github.com/thestinger/termite) which softwraps - the softwrapping is to blame for the partial repainting.

**Comment by 0xbaadf00d** [comment]
Same issue with single line and right prompt enabled

![image](https://cloud.githubusercontent.com/assets/1005086/17593579/a9f86682-5fe6-11e6-894b-422e52261a94.png)

**Comment by randomdude999** [comment]
@0xbaadf00d (I assume this happens when you shrinked the terminal window.) This happens with the right prompt probably because when you shrink the window, then the last character of the right prompt will be overflown into the next line. fish then proceeds to rewrite the prompt, but does not go to the previous line and writes it one the current one instead. This means that there is a bunch of garbage on the previous line that fish doesn't even know about. (This also happens to me <s>a lot</s> sometimes.)

**Comment by tamasgal** [comment]
I just wanted to let you know that this problem also exists in zsh for years, and almost every ohmyzsh theme I tested. The glitch also occurs on many single line prompts. I am "living" with this glitch for a couple of years already, from Mac OS 10.7 up to 10.12, using iTerm, iTerm2 and Terminal.app
I thought I could try fish to finally get rid of this and landed here ;)

**Comment by HolyGrace** [comment]
The problem is still relevant.
Terminal emulator -- Sakura
![2017-01-22-032045_700x419_scrot](https://cloud.githubusercontent.com/assets/8059773/22178782/eacbf836-e051-11e6-8be2-80bcb0fb03de.png)

**Comment by skerit** [comment]
This issue is still present in v2.6.0

**Comment by c02y** [comment]
This issue is still not fixed,  environment:

fish-shell v2.6.0
Konsole v2.3.3
CentOS 6.5 32-bit
TERM: xterm-256color

This annoy me for a long time (at least over a year), so I try to find a solution just now, and searching for solution leads me to this page.

Alternative solution:
When resizing panes, clear the other panes in the current window, but this is not a good solution.

**Comment by faho** [comment]
> Konsole v2.3.3

@c02y: Are you sure that's the version? Because according to https://cgit.kde.org/konsole.git/refs/tags, version 3.0.5 was released 15 years ago.

I can confirm that this does not happen with an up-to-date konsole, and I don't think we want to support terminals that are 15 years out of date.

Anyway, please test #4243.

**Comment by c02y** [comment]
@faho yes, Konsole v2.3.3, I'm using Linux Box in my company, and it is a very old of Linux distribution, it is chosen by my software development, I can not use the latest one.

![snapshot1](https://user-images.githubusercontent.com/2135996/28600363-175da04c-71e4-11e7-86de-00ba84cf00a7.png)

About the test, I installed (using yum) the stable version of fish-shell which is currently v2.6.0 from a [repo](http://download.opensuse.org/repositories/shells:/fish:/release:/2/CentOS_6/) for my version of Linux, and I cannot compile and install it from the source code directly since compiling requires higher version of tools.

g++ v4.4.7
clang++ v3.4.2
autoconf v2.69
automake v1.15

=============
**UPDATE**:

It took a while to install new version of gcc/g++ in my CentOS6.5 (instructions from [link](https://superuser.com/a/743163/151783). 

Before installing the #4243.
![recorded1](https://user-images.githubusercontent.com/2135996/28602603-a010257e-71f1-11e7-8c8a-6849b6f6e2d0.gif)
![recorded0](https://user-images.githubusercontent.com/2135996/28602604-a03ec866-71f1-11e7-93fe-d5fd5ffed9c3.gif)

After installing the #4243. I cannot say that it is fixed.
![recorded4](https://user-images.githubusercontent.com/2135996/28602708-1ec2d268-71f2-11e7-8517-f987e25d261f.gif)
![recorded3](https://user-images.githubusercontent.com/2135996/28602699-19127526-71f2-11e7-8bf8-fc0e7cc8c8a2.gif)

I'll let you know the result of another test in Fedora (new version of Konsole) when I get home.

**Comment by c02y** [comment]
This is the result of new konsole after installing the #4243.
Konsole v16.12.3

![recorded](https://user-images.githubusercontent.com/2135996/28622000-84ebe12a-71d8-11e7-9ce5-07a3a30f7b67.gif)
![recorded](https://user-images.githubusercontent.com/2135996/28622120-001f546c-71d9-11e7-9838-503ab2796427.gif)

I don't think it is fixed.

**Comment by faho** [comment]
@c02y: What's your `fish_prompt` function? Can you try without `fish_right_prompt`?

That is still broken for VTE-based terminals for me, so it's to be expected.

**Comment by c02y** [comment]
@faho It works good without `fish_right_prompt`.

**Comment by truenicoco** [comment]
Experiencing similar issue here with Fedora 27, i3-gaps 4.14.1 and xfce4-terminal 0.8.6 (Xfce 4.12).

**Comment by V0idk** [comment]
what's the solution? the pythonista.fish  do not have the fish_right_prompt

**Comment by faho** [comment]
It turns out the crashes in the test suite we've been getting with the previous attempts were because that sets $TERM to dumb. So we don't do this in dumb terminals, where it shouldn't have an effect anyway.

@V0idk: Rebuild fish with e35d248.
