### ISSUE TITLE
Conflicts with file from package docker-engine-1.8.2

### ISSUE THREAD

**Issue by s1rc0** [fish-shell/fish-shell#2436]
Error: Transaction check error:
  file /usr/share/fish/completions/docker.fish from install of fish-2.2.0-3.fc22.x86_64 conflicts with file from package docker-engine-1.8.2-1.fc22.x86_64

**Comment by faho** [comment]
Fedora?

That file in docker should go to /usr/share/fish/vendor_completions.d (which is "completionsdir" in pkg-config), though it's probably also okay to remove it from fish.

@amluto: You're the fish maintainer for Fedora, right? Mind taking a look?

**Comment by s1rc0** [comment]
Yes, Fedora22
Full log

```bash
~ ❯❯❯ sudo dnf install fish -y                                                                                                                                                                                                               
Last metadata expiration check performed 1:22:37 ago on Mon Sep 28 10:12:07 2015.
Dependencies resolved.
===============================================================================================================================================================================================================================================
 Package                                             Arch                                                  Version                                                  Repository                                                            Size
===============================================================================================================================================================================================================================================
Installing:
 fish                                                x86_64                                                2.2.0-3.1                                                shells_fish_release_2                                                1.2 M

Transaction Summary
===============================================================================================================================================================================================================================================
Install  1 Package

Total size: 1.2 M
Installed size: 5.3 M
Downloading Packages:
[SKIPPED] fish-2.2.0-3.1.x86_64.rpm: Already downloaded                                                                                                                                                                                       
Running transaction check
Transaction check succeeded.
Running transaction test
The downloaded packages were saved in cache till the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Transaction check error:
  file /usr/share/fish/completions/docker.fish from install of fish-2.2.0-3.1.x86_64 conflicts with file from package docker-engine-1.8.2-1.fc22.x86_64

Error Summary
-------------
```

**Comment by faho** [comment]
@s1rc0: You'll want to open a bug on the Fedora bugtracker for this - there's little influence we have here, especially when it comes to the docker packages.

As I said, the best solution would be to get docker-engine to put that file in vendor_completions.d, the second best to delete it from fish (because AFAIK it's now maintained in docker, we only carry it in case someone has an older docker version).

**Comment by amluto** [comment]
@s1rc0, you appear to have done:

    $ curl -sSL https://get.docker.com/ | sh

The real Fedora package (called docker, not docker-engine) doesn't have this bug.  I'll file an upstream bug with docker, though.

**Comment by s1rc0** [comment]
@amluto , The fact that this method installs the package docker-engine, not a docker
```javascript
[root@host user]# curl -sSL https://get.docker.com/ | sh

+ sh -c 'sleep 3; dnf -y -q install docker-engine'

If you would like to use Docker as a non-root user, you should now consider
adding your user to the "docker" group with something like:

  sudo usermod -aG docker your-user

Remember that you will have to log out and back in for this to take effect!
```

**Comment by amluto** [comment]
Indeed.  The "docker-engine" package, which is provided by upstream docker,
is buggy.  The "docker" package, which is provided and supported by Fedora,
is not buggy.

I filed an upstream bug: https://github.com/docker/docker/issues/16668

**Comment by faho** [comment]
Fixed in docker.

**Comment by s1rc0** [comment]
Thanks,
ok, wait for update docker package in F22 repo

**Comment by amluto** [comment]
@s1rc0, I think you may still be misunderstanding the bug.  There is no bug
in the F22 repo -- the bug is isolated to the Docker-provided RPM, which, I
would guess, is thoroughly incompatible with the RPMs in the F22 repo.

If you want immediate gratification, uninstall the docker RPM that you have
installed, remove the Docker-provided yum repo from your config, and then
install docker the Fedora-supported way using dnf.

**Comment by Assada** [comment]
Some error on Fedora23:
```
file /usr/share/fish/completions/docker.fish from install of docker-engine-1.9.1-1.fc23.x86_64 conflicts with file from package fish-2.2.0-4.fc23.x86_64
```

**Comment by zanchey** [comment]
Unfortunately, @amluto's advice still stands. I see you have noted that the upstream problem is not fixed in 1.9.1 and will only be in the 1.10 Docker release.

**Comment by phocean** [comment]
Unfortunately, there are other issues with the Docker version in Fedora 23 (like inability to log into the hub), so I won't follow @amluto's advice. Anyway, all these have clearly nothing to do with Fish. ;-)
