### ISSUE TITLE
Unexpected number of parameters to functions when invoked under `sh -a`

### ISSUE THREAD

**Issue by sanmai-NL** [fish-shell/fish-shell#3039]
Fish emits errors when launched under `sh -a`. I want to source a few variables and export them automatically within `sh`, then launch `fish` to inherit these environment variables.

### Reproduction Steps:

1. As unprivileged user, issue from a Fish shell:
```sh
sh -a -c '/usr/bin/fish -i' -i
```

### Expected behavior:

Normal interactive Fish shell.

### Observed behavior:

Slow interactive Fish shell that outputs a string of errors:
```
/usr/share/fish/config.fish (line 1): __fish_print_help --tty-width 238 function
                                      ^
in command substitution
        called on line -1 of file /usr/share/fish/config.fish

from sourcing file /usr/share/fish/config.fish
        called during startup

function: Expected one argument, got 4

/usr/share/fish/config.fish (line 24): function __fish_command_not_found_handler --on-event fish_command_not_found
    __fish_default_command_not_found_handler $argv
                                       ^
from sourcing file /usr/share/fish/config.fish
        called during startup

/usr/share/fish/functions/__fish_print_help.fish (line 1): __fish_print_help function
                                                           ^
in command substitution
        called on line -1 of file /usr/share/fish/functions/__fish_print_help.fish

from sourcing file /usr/share/fish/functions/__fish_print_help.fish
        called on line 1 of file /usr/share/fish/config.fish

in command substitution
        called on line -1 of file /usr/share/fish/config.fish

in command substitution
        called on line -1 of file /usr/share/fish/config.fish

from sourcing file /usr/share/fish/config.fish
        called during startup

function: Expected one argument, got 6

/usr/share/fish/functions/__fish_print_help.fish (line 1): function __fish_print_help --description "Print help message for the specified fish function or builtin" --argument item
        # special support for builtin_help_get()
                                                           ^
from sourcing file /usr/share/fish/functions/__fish_print_help.fish
        called on line 1 of file /usr/share/fish/config.fish

in command substitution
        called on line -1 of file /usr/share/fish/config.fish

in command substitution
        called on line -1 of file /usr/share/fish/config.fish

from sourcing file /usr/share/fish/config.fish
        called during startup

/usr/share/fish/config.fish (line 1): __fish_print_help --tty-width 238 function
                                      ^
in command substitution
        called on line -1 of file /usr/share/fish/config.fish

from sourcing file /usr/share/fish/config.fish
        called during startup

function: Expected one argument, got 6

/usr/share/fish/config.fish (line 103): function __fish_reconstruct_path -d "Update PATH when fish_user_paths changes" --on-variable fish_user_paths
        set -l local_path $PATH
                                        ^
from sourcing file /usr/share/fish/config.fish
        called during startup

/usr/share/fish/config.fish (line 122): __fish_reconstruct_path
                                        ^
from sourcing file /usr/share/fish/config.fish
        called during startup

/usr/share/fish/config.fish (line 1): __fish_print_help --tty-width 238 function
                                      ^
in command substitution
        called on line -1 of file /usr/share/fish/config.fish

from sourcing file /usr/share/fish/config.fish
        called during startup

function: Expected one argument, got 7

/usr/share/fish/config.fish (line 127): function fish_sigtrap_handler --on-signal TRAP --no-scope-shadowing --description "Signal handler for the TRAP signal. Launches a debug prompt."
        breakpoint
                                        ^
from sourcing file /usr/share/fish/config.fish
        called during startup

/usr/share/fish/config.fish (line 1): __fish_print_help --tty-width 238 function
                                      ^
in command substitution
        called on line -1 of file /usr/share/fish/config.fish

from sourcing file /usr/share/fish/config.fish
        called during startup

function: Expected one argument, got 4

/usr/share/fish/config.fish (line 136): function __fish_on_interactive --on-event fish_prompt
        __fish_config_interactive
                                        ^
from sourcing file /usr/share/fish/config.fish
        called during startup

/usr/share/fish/config.fish (line 1): __fish_print_help --tty-width 238 function
                                      ^
in command substitution
        called on line -1 of file /usr/share/fish/config.fish

from sourcing file /usr/share/fish/config.fish
        called during startup

function: Expected one argument, got 5

/usr/share/fish/config.fish (line 142): function . --description 'Evaluate contents of file (deprecated, see "source")' --no-scope-shadowing
        if begin
                                        ^
from sourcing file /usr/share/fish/config.fish
        called during startup

/usr/share/fish/functions/eval.fish (line 1): __fish_print_help function
                                              ^
in command substitution
        called on line -1 of file /usr/share/fish/functions/eval.fish

from sourcing file /usr/share/fish/functions/eval.fish
        called on line 1 of file ~/.config/fish/config.fish

in command substitution
        called on line -1 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
        called during startup

function: Expected one argument, got 5

/usr/share/fish/functions/eval.fish (line 1): function eval -S -d "Evaluate parameters as a command"
        # keep a copy of the previous $status and use restore_status
                                              ^
from sourcing file /usr/share/fish/functions/eval.fish
        called on line 1 of file ~/.config/fish/config.fish

in command substitution
        called on line -1 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
        called during startup

~/.config/fish/config.fish (line 4): eval (opam config --shell 'fish' env)
                                     ^
from sourcing file ~/.config/fish/config.fish
        called during startup

/usr/share/fish/functions/fish_mode_prompt.fish (line 1): __fish_print_help function
                                                          ^
in command substitution
        called on line -1 of file /usr/share/fish/functions/fish_mode_prompt.fish

from sourcing file /usr/share/fish/functions/fish_mode_prompt.fish
        called on standard input

in command substitution
        called on standard input

function: Expected one argument, got 4

/usr/share/fish/functions/fish_mode_prompt.fish (line 2): function fish_mode_prompt --description "Displays the current mode"
  # Do nothing if not in vi mode
                                                          ^
from sourcing file /usr/share/fish/functions/fish_mode_prompt.fish
        called on standard input

in command substitution
        called on standard input
```

#### Additional information ####

`man set` from the  POSIX Programmer's Manual:

`−a`    When this option is on, the export attribute shall be set for each variable to which an assignment is performed; see the Base Definitions volume of POSIX.1‐2008, Section 4.22, Variable Assignment. If the assignment precedes a utility name in a command, the export attribute shall not persist in the current execution environment after the utility completes, with the exception that preceding one of the special built-in utilities causes the export attribute to persist after the built-in has completed. If the assignment does not precede a utility name in the command, or if the assignment is a result of the operation of the getopts or read utilities, the export attribute shall persist until the variable is unset.

---

Fish version: 2.2.0

Operating system: Arch Linux, installed as package

Terminal or terminal emulator: Konsole

**Comment by faho** [comment]
I can reproduce in 2.2.0, but not in 2.3.0, so this is fixed.

I don't quite get what `set -a` is supposed to do, though, and why you'd want it.

**Comment by sanmai-NL** [comment]
`-a`: see the first sentences in my issue and the section 'Additional information' toward the end.

**Comment by zanchey** [comment]
I tend to agree, particularly as I can't reproduce it on 2.2.0. To start with, perhaps the output of `sh -a -c 'env' -i` might shed some light?

**Comment by sanmai-NL** [comment]
@zanchey: I can only send that to you in private, possibly. Perhaps your `sh` is `dash`?

```fish
  readlink -f (command -v sh)
```
```
/usr/bin/bash
```

`sh -a -c 'fish' -i`: issue ...
`dash -a -c 'fish' -i`: no issue!
`bash -a -c 'fish' -i`: no issue still!

**Comment by krader1961** [comment]
I cannot reproduce this on OS X, Ubuntu 14.04, or Cygwin. There's definitely something weird about your environment. What does `sh -a -c 'locale' -i` output?

**Comment by zanchey** [comment]
Bash behaves differently when it is called as `sh`, but yes - you are right. Dash is fine, bash-as-sh isn't!

The only difference I can see is that the dreaded `POSIXLY_CORRECT` variable is set when you use `sh` instead of `bash`, but that's the culprit: `env POSIXLY_CORRECT=y fish` is enough to make it blow up.

**Comment by zanchey** [comment]
OK, this is because when `POSIXLY_CORRECT` is set, `getopt` (and fish's `wgetopt` in 2.2) stops processing after the first non-option. This breaks all kinds of things in fish internally, and thankfully was removed in our implementation by f4d1657c22c81a7720a91026f915b80d2d6aa6e8, which will be in the next release.

@faho's instinct was correct!
