### ISSUE TITLE
changes needed to compile and run on illumos (nee OpenSolaris)

### ISSUE THREAD

**Issue by jblachly** [fish-shell/fish-shell#3340]
fish-shell will not compile on illumos (and probably not on Solaris) because this family of operating systems lacks the `MAP_FILE` flag for `mmap`. FreeBSD also lacks it according to my read of the manpage (although it may be defined somewhere for compatibility), so I am not sure how/if fish-shell builds on FreeBSD.

git commit 3702616b602c358062fc507729bc9b31a9ec2d60

`uname -a` output:

```
SunOS smartos-dev 5.11 joyent_20160731T153326Z i86pc i386 i86pc Solaris
```

fish-shell will not build because the mmap flag MAP_FILE is not defined on Solaris family operating systems. THis flag, which is a dummy, compatibility flag set to zero on all platforms for which it is defined (AFAIK), is included in the mmap call on line 1045 of `env_universal_common.cpp`.

By including

```
// Solaris family (e.g. illumos) doesn't have MAP_FILE
#ifndef MAP_FILE
#define MAP_FILE 0
#endif
```

at the beginning of `env_universal_common.h` fish-shell will now compile.

I have not made a pull request because I am new to the codebase and am not sure the most appropriate place for this #ifdef.

If this fix can get integrated, it opens up an entirely new pool of potential users. Once fish-shell builds straightforwardly I will push to get fish-shell in the illumos package repos.

Thanks for considering this.

**Comment by krader1961** [comment]
FWIW, It is rather strange that any UNIX derivative does not have a `MAP_FILE` symbol. Yes, strictly speaking, it is redundant since the default behavior of `mmap()` is to memory map a file. That's why it is zero on every platform I've ever used in the past 30+ years. Thus making it a no-op when or'd into a mask. You're proposal to add a fallback definition to *env_universal_common.h* seems fine to me.

Fish has built and run on Solaris in the past. Not sure what the current situation is. If you provide details about the errors you're seeing we can probably provide guidance.

**Comment by jblachly** [comment]
@krader1961 Thanks for your response (and changing issue title so I don't have to open a slew of issues).

I note that the `getcwd(NULL, 0)` call in `wutil.cpp` passes `0` for `size_t size`. This causes an **EINVAL** return on my platform. Reading the man page for linux, it appears that glibc extends the POSIX.1-2001 standard and allows a zero size in which case the buffer is allocated as large as is needed. However, this only works on glibc platforms.

Changing this parameter to PATH_MAX (defined in `limits.h` on most platforms, but also taken care of explicitly in your `wutil.cpp` file in case it is not defined by the platform) fixes the issue. 

Is it okay if I detail individual issues (and proposed fixes, if I know them) here, or should I open additional issues for better tracking?

**Comment by floam** [comment]
Maybe take a look over the autoconf macros commonly uses to check for this one and see how it's commonly dealt with - it's something we don't do enough of, frankly - there are a few things it resolves for us we haven't quite "hooked up" to the macros they set for us after pretty great tests.

**Comment by jblachly** [comment]
@floam I have to say that I never did learn the autconf and other build tools, but I'll give it a go.

FWIW, I am initiating a pull request for illumos-gate to add MAP_FILE to mman.h, but Oracle Solaris 11.3 latest still does not include it AFAIK, so an autoconf detection will still be nice

**Comment by floam** [comment]
FWIW: [Austin Group references mmap-anon.m4](http://austingroupbugs.net/view.php?id=850). ([mirrored here](https://github.com/coreos/grub/blob/master/m4/mmap-anon.m4)).

**Comment by krader1961** [comment]
@jblachly Whether or not we tackle all the illumos (nee OpenSolaris) problems in this issue or separate issues depends on whether we expect there to be more than one or two non-trivial problems. The lack of `MAP_FILE` is a trivial problem with a trivial, obvious, fix. Something like the `getcwd()` problem is non-trivial.

The `getcwd()` failure is interesting. Since we're explicitly passing a NULL pointer for the buffer we're telling the implementation to allocate an appropriately sized buffer and thus a size of zero is reasonable. On the other hand I found at least one [Open Group standard](http://pubs.opengroup.org/onlinepubs/9699919799/functions/getcwd.html) that says "If buf is a null pointer, the behavior of getcwd() is unspecified." So, like so many things of this nature, the question is how best to support multiple platforms that conform to different standards. Note that the `man getcwd` man page on macOS Sierra says that the function returns `EINVAL` if the size argument is zero. Yet it obviously does not since I'm successfully using fish on that OS.

There is also this [interesting blog article](http://insanecoding.blogspot.com/2007/11/pathmax-simply-isnt.html) about their real world experience dealing with APIs like `getcwd()` and `PATH_MAX`. On OS X (even the beta macOS Sierra build) `PATH_MAX` is 1024. Which is absurd. So it's not obvious that replacing that zero with `PATH_MAX` in the `getcwd()` call is the right thing to do on all platforms. 

Fantastic! Even the fish source code is schizophrenic about `PATH_MAX`. Just look at how it's used in *src/fish_tests.cpp*. &lt;/face-palm&gt;

**Comment by jblachly** [comment]
@krader1961 I will take you up on your offer for me to detail the errors I'm seeing for your guidance. I will be happy to open additional tickets, but also to perform any work on my end to help track these down. Please keep in mind although I can stumble about in C and C++, I do not consider myself a systems programmer. My level of sophistication with debugging in C is stuck at the "include extra verbose debug logging". **To that end, I did overload and modify the `wperror()` function to report the function from which it was called -- can I provide that code here or should I fork and make pull request?**

Using the github commit referenced at the top of this issue:
* First, it fails to compile unless I define `MAP_FILE`. I am taking care of this at my OS level, but I think this will still be a problem on Solaris.

* After fixing that it builds, but there is a `getcwd` error when running:
```
% ./fish
<E> fish: getcwd() failed with errno 22/Invalid argument
<E> fish: Could not determine current working directory. Is your locale set correctly?
<W> fish: Unable to parse universal variable message: 'SET __fish_init_2_3_0:\x1d'
<E> fish: getcwd() failed with errno 22/Invalid argument
...many, many lines (see later)
<W> fish: Unable to parse universal variable message: 'SET __fish_init_2_3_0:\x1d'
<E> fish: getcwd() failed with errno 22/Invalid argument
@ > <E> fish: getcwd() failed with errno 22/Invalid argument
@ >
```
* I have already detailed how to fix this problem (`PATH_MAX`)

* After fixing the `getcwd` problem and recompiling, here is the output (and where I am stuck):
```
% ./fish
<W> fish: Unable to parse universal variable message: 'SET __fish_init_2_3_0:\x1d'
<W> fish: Unable to parse universal variable message: 'SET __fish_init_2_3_0:\x1d'
<W> fish: Unable to parse universal variable message: 'SET fish_greeting:Welcome\x20to\x20fish\x2c\x20the\x20friendly\x20interactive\x20shell\x0aType\x20\x1b\x5b32mhelp\x1b\x5b30m\x1b\x28B\x1b\x5bm\x20for\x20instructions\x20on\x20how\x20to\x20use\x20fish'
<W> fish: Unable to parse universal variable message: 'SET __fish_init_1_50_0:\x1d'
<W> fish: Unable to parse universal variable message: 'SET fish_color_normal:normal'
<W> fish: Unable to parse universal variable message: 'SET fish_color_command:brblue'
<W> fish: Unable to parse universal variable message: 'SET fish_color_param:cyan'
<W> fish: Unable to parse universal variable message: 'SET fish_color_redirection:normal'
<W> fish: Unable to parse universal variable message: 'SET fish_color_comment:red'
<W> fish: Unable to parse universal variable message: 'SET fish_color_error:red\x1e\x2d\x2dbold'
<W> fish: Unable to parse universal variable message: 'SET fish_color_escape:cyan'
<W> fish: Unable to parse universal variable message: 'SET fish_color_operator:cyan'
<W> fish: Unable to parse universal variable message: 'SET fish_color_end:green'
<W> fish: Unable to parse universal variable message: 'SET fish_color_quote:brown'
<W> fish: Unable to parse universal variable message: 'SET fish_color_autosuggestion:brgrey'
<W> fish: Unable to parse universal variable message: 'SET fish_color_user:green'
<W> fish: Unable to parse universal variable message: 'SET fish_color_host:normal'
<W> fish: Unable to parse universal variable message: 'SET fish_color_valid_path:\x2d\x2dunderline'
<W> fish: Unable to parse universal variable message: 'SET fish_color_cwd:green'
<W> fish: Unable to parse universal variable message: 'SET fish_color_cwd_root:red'
<W> fish: Unable to parse universal variable message: 'SET fish_color_match:cyan'
<W> fish: Unable to parse universal variable message: 'SET fish_color_search_match:\x2d\x2dbackground\x3dpurple'
<W> fish: Unable to parse universal variable message: 'SET fish_color_selection:\x2d\x2dbackground\x3dpurple'
<W> fish: Unable to parse universal variable message: 'SET fish_pager_color_prefix:cyan'
<W> fish: Unable to parse universal variable message: 'SET fish_pager_color_completion:normal'
<W> fish: Unable to parse universal variable message: 'SET fish_pager_color_description:brgrey'
<W> fish: Unable to parse universal variable message: 'SET fish_pager_color_progress:cyan'
<W> fish: Unable to parse universal variable message: 'SET fish_color_history_current:cyan'
There is no fish_key_bindings function called: 'fish_default_key_bindings'
Reverting to default bindings
<W> fish: Unable to parse universal variable message: 'SET fish_key_bindings:fish_default_key_bindings'
<W> fish: Unable to parse universal variable message: 'SET fish_key_bindings:fish_default_key_bindings'
There is no fish_key_bindings function called: ''
Reverting to default bindings

(previous 2 lines repeated 125 times...I think)

The function call stack limit has been exceeded. Do you have an accidental infinite loop?
fish: __fish_reload_key_bindings VARIABLE SET fish_key_bindings
      ^
in event handler: handler for variable 'fish_key_bindings'

There is no fish_key_bindings function called: ''
Reverting to default bindings

(previous 2 lines repeated approximately 9x10^zillion times)

The function call stack limit has been exceeded. Do you have an accidental infinite loop?
fish: __fish_reload_key_bindings VARIABLE SET fish_key_bindings
      ^
in event handler: handler for variable 'fish_key_bindings'

<W> fish: Unable to parse universal variable message: 'SET __fish_init_2_3_0:\x1d'
@ ~/home/james/source/fish-shell>
``` 

From here I have a shell and can execute external commands, but command completion routines in `path.cpp:path_get_path_core` cause a lot of pain:
```
@ ~/home/james/source/fish-shell> l<W> fish: Error while searching for command '/usr/xpg4/bin/l'
access: No such file or directory
<W> fish: Error while searching for command '/usr/local/sbin/l'
access: No such file or directory
<W> fish: Error while searching for command '/usr/local/bin/l'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/sbin/l'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/bin/l'
access: No such file or directory
<W> fish: Error while searching for command '/usr/sbin/l'
access: No such file or directory
<W> fish: Error while searching for command '/usr/bin/l'
access: No such file or directory
<W> fish: Error while searching for command '/sbin/l'
access: No such file or directory
ls
autom4te.cache           config.status            Dockerfile               fish_tests               Makefile                 src
build_tools              config.sub               Doxyfile                 FISH-BUILD-VERSION-FILE  Makefile.in              test
CHANGELOG.md             configure                Doxyfile.help            fish.pc                  obj                      tests
config.guess             configure.ac             Doxyfile.user            fish.pc.in               osx
config.h                 CONTRIBUTING.md          etc                      fish.spec.in             pcre2-10.21
config.h.in              COPYING                  fish                     fish.xcodeproj           po
config.h.in~             debian                   fish_indent              install-sh               README.md
config.log               doc_src                  fish_key_reader          lexicon_filter.in        share
@ ~/home/james/source/fish-shell>
```

I have done further amateur debugging (really, it's way past time I learned to use gdb) by emitting specific errno's and can make some conclusions about why this may be happening, but I will stop here in case you as the experts have any insights.

Thanks again and let me know if I should break this into separate issues, or if I can do any debugging on your behalf. Kind regards.

**Comment by faho** [comment]
>The function call stack limit has been exceeded. Do you have an accidental infinite loop?
fish: __fish_reload_key_bindings VARIABLE SET fish_key_bindings

This looks like what happened on #3302, and it would also explain the later issues.

What's your `locale`? In 3302, it seemed to be related to FreeBSD's unicode handling - which lead to some truly bizarre issues.

Also, if you try fish from git you'll get a less verbose failure for __fish_reload_key_bindings.

**Comment by jblachly** [comment]
@faho, my fish was compiled directly from git master 3702616b602c358062fc507729bc9b31a9ec2d60 (now only one commit behind).  I did run `./fish` , but had previously `sudo make install`'ed ; the errors and warnings are the same even if running from `/opt/local/bin`.

Will check my locale settings when I get home tonight.

**Comment by faho** [comment]
From @floam's screencast in #3302, I think I might know why my fix is not working.

Can you confirm that `functions -q fish_default_key_bindings; echo $status` prints 0, but `set -l foo fish_default_key_bindings; functions -q "$foo"; echo $status` prints 1? Please enter this exactly as it is, it appears on both FreeBSD and Illumos we have some issues with Unicode that result in variables in quotes being expanded to nothing.

**Comment by jblachly** [comment]
(While prepping this message, I discovered that `history --clear` does not work on my platform)

@faho :  Apologies in advance for the lengthy report. I pasted versions without the erroneous "Error while searching for..." failed completion as well, but wanted to also emphasize the problem of failures during command-completion on illumos (which AFAICT may be related in part, but not entirely, to non threadsafe errno ?)

**Bottom line:** The commands you suggested report `0` and `1` as you expected. Looks like the illumos troubles stem from elsewhere -- unrelated to FreeBSD problems ... sorry :|

Form one (without set foo)
```
@ ~/home/james/source/fish-shell> f<W> fish: Error while searching for command '/usr/xpg4/bin/f'
access: No such file or directory
<W> fish: Error while searching for command '/usr/local/sbin/f'
access: No such file or directory
<W> fish: Error while searching for command '/usr/local/bin/f'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/sbin/f'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/bin/f'
access: No such file or directory
<W> fish: Error while searching for command '/usr/sbin/f'
access: No such file or directory
<W> fish: Error while searching for command '/usr/bin/f'
access: No such file or directory
<W> fish: Error while searching for command '/sbin/f'
access: No such file or directory
fu<W> fish: Error while searching for command '/usr/xpg4/bin/fu'
access: No such file or directory
<W> fish: Error while searching for command '/usr/local/sbin/fu'
access: No such file or directory
<W> fish: Error while searching for command '/usr/local/bin/fu'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/sbin/fu'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/bin/fu'
access: No such file or directory
<W> fish: Error while searching for command '/usr/sbin/fu'
access: No such file or directory
<W> fish: Error while searching for command '/usr/bin/fu'
access: No such file or directory
<W> fish: Error while searching for command '/sbin/fu'
access: No such file or directory
functions <W> fish-: Error while searching for command '/usr/xpg4/bin/functions'
access: No such file or directory
<W> fish: Error while searching for command '/usr/local/sbin/functions'
access: No such file or directory
<W> fish: Error while searching for command '/usr/local/bin/functions'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/sbin/functions'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/bin/functions'
-access: No such file or directory
<W> fish: Error while searching for command '/usr/sbin/functions'
access: No such file or directory
<W> fish: Error while searching for command '/usr/bin/functions'
access: No such file or directory
<W> fish: Error while searching for command '/sbin/functions'
access: No such file or directory
q fish_default_key_bindings; echo $status
0
```

(now without errors)
```
@ ~/home/james/source/fish-shell> functions -q fish_default_key_bindings; echo $status
0
``` 

Form two (with set foo)
```
@ ~/home/james/source/fish-shell> <W> sfish: Error while searching for command '/usr/xpg4/bin/s'
access: No such file or directory
<W> fish: Error while searching for command '/usr/local/sbin/s'
access: No such file or directory
<W> fish: Error while searching for command '/usr/local/bin/s'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/sbin/s'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/bin/s'
access: No such file or directory
<W> fish: Error while searching for command '/usr/sbin/s'
access: No such file or directory
<W> fish: Error while searching for command '/usr/bin/s'
access: No such file or directory
<W> fish: Error while searching for command '/sbin/s'
access: No such file or directory
se<W> fish: Error while searching for command '/usr/xpg4/bin/se'
access: No such file or directory
<W> fish: Error while searching for command '/usr/local/sbin/se'
access: No such file or directory
<W> fish: Error while searching for command '/usr/local/bin/se'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/sbin/se'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/bin/se'
access: No such file or directory
<W> fish: Error while searching for command '/usr/sbin/se'
access: No such file or directory
<W> fish: Error while searching for command '/usr/bin/se'
access: No such file or directory
<W> fish: Error while searching for command '/sbin/se'
access: No such file or directory
set <W> fish: Error while searching for command '/usr/xpg4/bin/set'
access: -No such file or directory
<W> fish: Error while searching for command '/usr/local/sbin/set'
access: No such file or directory
<W> fish: Error while searching for command '/usr/local/bin/set'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/sbin/set'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/bin/set'
access: No such file or directory
<W> fish: Error while searching for command '/usr/sbin/set'
-access: No such file or directory
<W> fish: Error while searching for command '/usr/bin/set'
access: No such file or directory
<W> fish: Error while searching for command '/sbin/set'
access: No such file or directory
l foo fish_default_key_bindings; f<W> fish: Error while searching for command '/usr/xpg4/bin/fu'
access: No such file or directory
u<W> fish: Error while searching for command '/usr/local/sbin/fu'
access: No such file or directory
<W> fish: Error while searching for command '/usr/local/bin/fu'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/sbin/fu'
access: No such file or directory
<W> fish: Error while searching for command '/opt/local/bin/fu'
access: No such file or directory
<W> fish: Error while searching for command '/usr/sbin/fu'
access: No such file or directory
<W> fish: Error while searching for command '/usr/bin/fu'
access: No such file or directory
<W> fish: Error while searching for command '/sbin/fu'
access: No such file or directory
functions -q "$foo"; echo $status
1
```

And now succinctly removing the error messages:
```
@ ~/home/james/source/fish-shell> set -l fish_default_key_bindings; functions -q "$foo"; echo $status
1
```

**Comment by jblachly** [comment]
So although I doubt this will solve all my fish woes, I found an error in my platform's implementation of `wcsncasecmp` and have filed an issue.

Let's put debugging for this platform on hold until I get that sorted out. There are definitely other problems that I would like to get fixed; I appreciate everyone's help and I am very much looking forward to trying the fish shell.

**Comment by faho** [comment]
>Bottom line: The commands you suggested report 0 and 1 as you expected. Looks like the illumos troubles stem from elsewhere -- unrelated to FreeBSD problems ... sorry :|

What I expected was just what happens with FreeBSD. They are related.

The issue is that a variable inside quotes expands to nothing. That's just like #3302.

**Comment by jblachly** [comment]
Sorry then, misunderstood your expected results. So if this explains the lack of default keybindings , and the illumos `wcsncasecmp` error explains my failure to properly evaluate `SET` statements perhaps I am closer than I think.

**Comment by jblachly** [comment]
Updates:

[I patched illumos to include MAP_FILE] (https://github.com/illumos/illumos-gate/commit/ccd5347f5bded380cdbfc73f87db15cfd5610961)  as a flag for mmap, although I see that @zanchey  made a commit to get rid of that in the interim.

Robert Mustacchi of Joyent verified the `wcsncasecmp` bug and [patched it in illumos](https://github.com/illumos/illumos-gate/commit/f2d34afa1058d195513e7ab9a6c1f0ce38b4d05b)

**This improves interactive behavior including command suggestion noticeably** for the build I was working on at the time I opened this issue at beginning of September. ( 3702616b602c358062fc507729bc9b31a9ec2d60 )

However, **the fish-shell current  HEAD (master) will not build**, so I performed a `git bisect`. The change to clang (06c658dd5e8d331badd0589274e061b28e1eaac8) is the first commit that fails to build on illumos:

```
(warnings removed)
  CXX = 'clang++'
  CXXFLAGS = '-g -O2 -fno-exceptions -Wextra -Ipcre2-10.21/src '
  MKDIR_P = '/opt/local/bin/mkdir -p'
  mkdir    obj
  CPPFLAGS = '-DLOCALEDIR="/usr/local/share/locale" -DPREFIX=L"/usr/local" -DDATADIR=L"/usr/local/share" -DSYSCONFDIR=L"/usr/local/etc" -DBINDIR=L"/usr/local/bin" -DDOCDIR=L"/usr/local/share/doc/fish" -iquote. -iquote./src/ -DFISH_BUILD_VERSION="2.3.1-543-g06c658d"'
  CXX      obj/fish.o
... (warnings removed)...
  CXX      obj/builtin_set_color.o
src/builtin_set_color.cpp:144:9: error: use of undeclared identifier 'cur_term'
    if (cur_term == NULL && setupterm(0, STDOUT_FILENO, &errret) == ERR) {
        ^
src/builtin_set_color.cpp:151:10: error: use of undeclared identifier 'exit_attribute_mode'
    if (!exit_attribute_mode) {
         ^
src/builtin_set_color.cpp:163:13: error: use of undeclared identifier 'enter_bold_mode'
        if (enter_bold_mode) writembs(tparm(enter_bold_mode));
            ^
src/builtin_set_color.cpp:163:45: error: use of undeclared identifier 'enter_bold_mode'
        if (enter_bold_mode) writembs(tparm(enter_bold_mode));
                                            ^
./src/output.h:32:39: note: expanded from macro 'writembs'
#define writembs(mbs) writembs_check((mbs), #mbs, __FILE__, __LINE__)
                                      ^
src/builtin_set_color.cpp:167:13: error: use of undeclared identifier 'enter_underline_mode'
        if (enter_underline_mode) writembs(enter_underline_mode);
            ^
src/builtin_set_color.cpp:167:44: error: use of undeclared identifier 'enter_underline_mode'
        if (enter_underline_mode) writembs(enter_underline_mode);
                                           ^
./src/output.h:32:39: note: expanded from macro 'writembs'
#define writembs(mbs) writembs_check((mbs), #mbs, __FILE__, __LINE__)
                                      ^
src/builtin_set_color.cpp:173:28: error: use of undeclared identifier 'exit_attribute_mode'
            writembs(tparm(exit_attribute_mode));
                           ^
./src/output.h:32:39: note: expanded from macro 'writembs'
#define writembs(mbs) writembs_check((mbs), #mbs, __FILE__, __LINE__)
                                      ^
src/builtin_set_color.cpp:180:28: error: use of undeclared identifier 'exit_attribute_mode'
            writembs(tparm(exit_attribute_mode));
                           ^
./src/output.h:32:39: note: expanded from macro 'writembs'
#define writembs(mbs) writembs_check((mbs), #mbs, __FILE__, __LINE__)
                                      ^
8 errors generated.
Makefile:801: recipe for target 'obj/builtin_set_color.o' failed
make: *** [obj/builtin_set_color.o] Error 1
``` 

The changes were to `Makefile.in` and `configure.ac`. I looked through them briefly but as I know neither clang nor autotools well, I did not see any obvious culprit.

Once again, I really appreciate everyone's help and suggestions. I want to see this port through to the end but need help with a few of the hurdles.

**Comment by zanchey** [comment]
It might be worth trying to build with your standard system compiler (GCC?) rather than LLVM; I don't know why the change was made.

Perhaps try:
`./configure CXX=gcc; make`
and if that's no good then
`./configure; make V=1`
to get a full verbose log; if you can paste the verbose log into a gist then we can look through it.

**Comment by jblachly** [comment]
@zanchey Compiles with g++. I will try to track down the clang issue eventually but higher priority is fixing what looks like some platform differences in syscalls (getcwd seems problematic for one). Thanks everyone for your help so far.

**Comment by zanchey** [comment]
Could you try #3608? That produces a working binary for me on Solaris 11.

**Comment by jblachly** [comment]
@zanchey Accidentally commented on #3608 instead of here.

Bottom line, latest commit compiles great; I included a short patch (below) to fix a `getcwd` error that I previously mentioned. 👍 

Fix that and we are nearly 100% functional on illumos. I now need to track down some kind of ANSI error. 

```
james@fish-build:~/fish-shell$ git diff
diff --git a/src/wutil.cpp b/src/wutil.cpp
index 3d8c914..2cff992 100644
--- a/src/wutil.cpp
+++ b/src/wutil.cpp
@@ -129,7 +129,7 @@ bool wreaddir_for_dirs(DIR *dir, wcstring *out_name) {
 const wcstring wgetcwd() {
     wcstring retval;

-    char *res = getcwd(NULL, 0);
+    char *res = getcwd(NULL, PATH_MAX);
     if (res) {
         retval = str2wcstring(res);
         free(res);
```

**Comment by krader1961** [comment]
One of the relevant standards for [getcwd()](http://pubs.opengroup.org/onlinepubs/009695399/functions/getcwd.html) says that passing NULL for the buffer isn't required to be supported. And if we have to specify a maximum length we might as well allocate the buffer ourself. Also, looking at our code we are inconsistent about how we invoke `getcwd()` (do `grep PATH_MAX src/*`). That should also be fixed by normalizing on a single pattern. Perhaps even creating a `fish_getcwd()` to ensure we have a single implementation the rest of fish can use.

**Comment by jblachly** [comment]
Re. the ANSI escape code and unicode character output between commands, e.g.:
```
james@fish-build:~/fish-shell$ fish
30m30m⏎
james@fish-build ~/fish-shell>
30m⏎
james@fish-build ~/fish-shell> echo "hello world"
30mhello world
30m⏎
```

I tracked it down with `git bisect` to the following commit: 01dbfb0a3f62c5a2765fbed481e17752191ac755

The changes are in `reader.cpp` ; I will do some further digging to see what's up.

The unicode "return arrow" comes from common.cpp:
`omitted_newline_char = can_be_encoded(L'\x23CE') ? L'\x23CE' : L'~';`

But I'm not sure why the \e30m reset is being displayed before every line (note that it appears before the 'hello world' output) nor why the unicode return arrow is being displayed every time immediately prior to a prompt. BEL (\a) is also being emitted audibly. 

I should also note that apart from this, colors work perfectly well , so hopefully that will make it easier to track down -- in `src/reader.cpp` ?

**Comment by krader1961** [comment]
No need, @jblachly. The problem is that some libc implementations don't allow mixing narrow and wide stdio functions on the same stream. BSD, where I tested that change, does allow you to mix them. A fix for that issue was merged a couple of hours ago.

**Comment by jblachly** [comment]
@krader1961 Unfortunately that commit doesn't fix the behavior I'm seeing over here.

**Comment by krader1961** [comment]
The `\e30m` sequence on most terminals sets the foreground color to black; e.g., `set_color black` or equivalent. Ignore the return arrow as that just means the last line of output from the previous command did not end with a newline. It's just a symptom of the real problem.

Please run `script typescript.txt fish` then `exit` and attach the *typescript.txt* file to this issue.

Also, when you say "that commit" do you mean 1621fa43? If you're running a fish with that fix I don't see how the other changes in commit 01dbfb0 could possibly account for the problem you're seeing.

**Comment by zanchey** [comment]
> Perhaps even creating a fish_getcwd() to ensure we have a single implementation the rest of fish can use.

SGTM

**Comment by jblachly** [comment]
Some commit between Dec 29 and now fixed the problem with the ANSI escape code being displayed.

The only outstanding issues I found on a first pass are:
1. `getcwd` (which I patch on my end to pass `PATH_MAX` instead of 0 as second param) and
2. `make install` having some difficulty installing man pages which I haven't tracked down yet.

V. excited to get fish shell working on illumos! Thanks so much for your great work along the way.

Likely, passing PATH_MAX is reasonable solution (and it is used in wgetrealpath anyway). If you want to tackle the NULL issue and allocate the buffer yourself, could we at least pass nonzero for the buflen in the meantime to maximize compatibility?

**Comment by 3eka** [comment]
Hi all,
I just entered into this discussion and wonder what is status?

I am running OpenIndiana (OI) OS (https://www.openindiana.org/) which is built on top of Illumos...

Tried to compile fish-2.5.0 (./configure --prefix=/opt/SFW; that prefix is in PATH) and have entered to few issues:
```
checking term.h presence... yes
configure: WARNING: term.h: present but cannot be compiled
configure: WARNING: term.h:     check for missing prerequisite headers?
configure: WARNING: term.h: see the Autoconf documentation
configure: WARNING: term.h:     section "Present But Cannot Be Compiled"
configure: WARNING: term.h: proceeding with the compiler's result
configure: WARNING:     ## ----------------------------------------------- ##
configure: WARNING:     ## Report this to fish-users@lists.sourceforge.net ##
configure: WARNING:     ## ----------------------------------------------- ##
```
Not sure if term.h issue is important?
```
$ gmake
  FISH_BUILD_VERSION = '2.5.0'
  CXX = '/usr/gcc/5/bin/g++ -std=c++11'
  CXXFLAGS = '-g -O2 -fno-exceptions -Wextra -pthread -Ipcre2-10.21/src '
  MKDIR_P = '/usr/gnu/bin/mkdir -p'
  SED = '/usr/gnu/bin/sed'
  AWK = 'gawk'
  FGREP = '/usr/gnu/bin/grep -F'
  doxygen  user_doc
sh: line 1: ./lexicon_filter: cannot execute [Permission denied]
  prefix = '/opt/SFW'
  sysconfdir = '/opt/SFW/etc'
  docdir = '/opt/SFW/share/doc/fish'
  extra_completionsdir = '/opt/SFW/share/fish/vendor_completions.d'
  extra_functionsdir = '/opt/SFW/share/fish/vendor_functions.d'
  extra_confdir = '/opt/SFW/share/fish/vendor_conf.d'
$ chmod 755 ./lexicon_filter
$ pfexec gmake install
  FISH_BUILD_VERSION = '2.5.0'
  CXX = '/usr/gcc/5/bin/g++ -std=c++11'
  CXXFLAGS = '-g -O2 -fno-exceptions -Wextra -pthread -Ipcre2-10.21/src '
  MKDIR_P = '/usr/gnu/bin/mkdir -p'
  SED = '/usr/gnu/bin/sed'
  AWK = 'gawk'
  FGREP = '/usr/gnu/bin/grep -F'
  doxygen  user_doc
/nobackup/Build/fish-2.5.0/doc.h:6189: warning: Reached end of file while still inside a (nested) comment. Nesting level 1 (probable line reference: 1)
  prefix = '/opt/SFW'
  sysconfdir = '/opt/SFW/etc'
  docdir = '/opt/SFW/share/doc/fish'
  extra_completionsdir = '/opt/SFW/share/fish/vendor_completions.d'
  extra_functionsdir = '/opt/SFW/share/fish/vendor_functions.d'
  extra_confdir = '/opt/SFW/share/fish/vendor_conf.d'
fish has now been built.
Run gmake install to install fish.
  HAVE_GETTEXT = '1'
Installing translations...
  datadir = '/opt/SFW/share'
  mandir = '/opt/SFW/share/man'
 Installing fish
 Installing fish_indent
 Installing fish_key_reader
Creating sysconfdir tree  
Creating datadir tree
Creating placeholder vendor/'extra_' directories
Installing pkgconfig file 
Installing the fish completion library...
Installing fish functions
Installing man pages
Installing helper tools
Installing online user documentation
Installing more man pages
/usr/gnu/bin/install: cannot stat 'share/man/man1/fish.1': No such file or directory
/usr/gnu/bin/install: cannot stat 'share/man/man1/fish_indent.1': No such file or directory
/usr/gnu/bin/install: cannot stat 'share/man/man1/fish_key_reader.1': No such file or directory
Checking for legacy binaries...

fish is now installed on your system.
To run fish, type fish in your terminal.
Even if you are already in fish, you should now start a new fish session.

To set your colors, run fish_config
To scan your man pages for completions, run fish_update_completions
To accept autosuggestions (in grey) as you type, hit ctrl-F or right arrow key.

Have fun! <><
```
Had to change permissions of lexicon_filter to 775 (that should be easy to fix).
Not sure about failing to build man pages...

When running **fish**:
```
$ rm -rf ~/.config/fish/
$ fish
<E> fish: getcwd() failed with errno 22/Invalid argument
<E> fish: Could not determine current working directory. Is your locale set correctly?
<E> fish: getcwd() failed with errno 22/Invalid argument
<E> fish: getcwd() failed with errno 22/Invalid argument
```
This is really annoying and I wonder if MAX_PATH fix (from top of discussion) is still relevant (or it has to be added to source)?

I have got same results when trying to build from git clone source tree.

This looks very interesting and I would like to have it working on OI...

Thanks and best regards.

**Comment by jblachly** [comment]
@3eka PATH_MAX (see my post above yours) will fix the getcwd problem. It has not been incorporated into tree

**Comment by mqudsi** [comment]
[The standard is pretty clear](http://pubs.opengroup.org/onlinepubs/9699919799/) that these arguments have to be specified. What we're doing is definitely not portable (even if it's very common).

It seems that fish uses `wgetcwd()` throughout, which is a wrapper for `getcwd()` anyway... Makes it really easy to fix.
