### ISSUE TITLE
Windows 10 Bash crashed after fish installed

### ISSUE THREAD

**Issue by pwwang** [fish-shell/fish-shell#4138]
You probably know that Windows 10 supports a bash prompt from Ubuntu.
I try to install fish on it: 
```bash
sudo apt-get install fish
```
And then I exit the terminal, and try to open it again using "bash.exe", but faileld.
I can't open the terminal, so I don't know the fish version...

PS: I tried "bash.exe" in "cmd.exe", it showed "Error: 0x80070005"

**Comment by krader1961** [comment]
I don't know what else you did but simply installing fish did not break your Windows Subsystem for Linux (aka "bash on linux on windows"). I did exactly what you said you did and have no trouble starting a new WSL session or running `bash.exe` from a PowerShell window.

Also, the version installed by the command you ran is fish 2.0. That is extremely old. We just released fish 2.6. And while that old version works fine we're not going to be able to help very much with any issues you encounter.

**Comment by pwwang** [comment]
@krader1961 I didn't do anything else. I just git-cloned a repository. I tried to re-install the WSL, but still failed to open the bash terminal.

**Comment by krader1961** [comment]
> I just git-cloned a repository.

That is not what you said in your original problem statement. You said you ran `sudo apt-get install fish`. That does not clone a git repository. You also say you tried to re-install WSL but did not provide any details. Did you do what was documented [here](https://www.howtogeek.com/261188/how-to-uninstall-or-reinstall-windows-10s-ubuntu-bash-shell/)?

Note that a Google search for "Error: 0x80070005" says that means "ACCESS DENIED". It is well nigh impossible that installing fish could cause that problem. You are probably going to get better advice in a MS Windows support forum.

**Comment by pwwang** [comment]
@krader1961 You asked me what else I did. By "I just git-cloned a repository", I meant after I installed WSL, and before I installed fish, that the only thing I did. After I installed fish, I just tried to restart the terminal, but failed. Well, I didn't follow the document to uninstall it, I uninstalled it via control panel. I will try to figure out something behind and keep you updated. Thanks anyway.

**Comment by krader1961** [comment]
FWIW, I've been building and running fish on WSL for more than year. I've never seen anything remotely like what you are describing. Regardless of whether I use the version installed by `sudo apt-get install fish` or the version from cloning and building https://github.com/fish-shell/fish-shell.git. And given what I know about MS Windows and fish it is impossible for merely installing fish to cause the problem you are describing. At least without a serious bug in the WSL environment.

**Comment by krader1961** [comment]
I'm going to leave this open, despite what I just wrote in my previous comment, because I would like us get to the root cause of the problem. So as to help future users of fish on WSL.

**Comment by pwwang** [comment]
Just in case if someone encounters this suitation:  
I followed [this instruction](https://github.com/Microsoft/BashOnWindows/issues/473) to reinstall WSL. Note that you have to delete the folder `%localappdata%\lxss\temp` before you install WSL (by this, you will lost your linux data!!). After WSL is installed, immediately do `sudo apt-get install fish`.  
I am not sure if it was caused by fish. I am closing it for now, please feel free to re-open it if you have this situation.

**Comment by krader1961** [comment]
You wrote:

> After WSL is installed, immediately do `sudo apt-get install fish`.

It is unclear if you mean that reproduces the problem or gives you a working fish shell you can run by typing `/usr/bin/fish`. You do seem to be saying that reinstalling WSL and then fish works without error. Yes?

If that is true then possibly you inadvertently did something to break WSL other than merely installing fish. Alternatively your hardware might have an intermittent failure.

**Comment by pwwang** [comment]
Yes, after WSL is reinstalled, then I immediately install fish, and fish works without error.  
I have a guess in mind, but am not so sure about it. I used vscode as the editor to edit some files inside the linux system, which is at `C:\Users\<user>\AppData\Local\lxss\home\<lxuser>`. Vscode integrates git, which was installed on Windows system. So some files, created by a windows user in the linux system, are not full accessible by linux users. That might be the reason to cause WSL crashes and shows "Access denied" error code.  
Maybe I can see if I can reproduce this.
