### ISSUE TITLE
invocation tests fail if fish is installed into /bin

### ISSUE THREAD

**Issue by gyakovlev** [fish-shell/fish-shell#4883]
fish version - latest master available (https://github.com/fish-shell/fish-shell/commit/366933413bb448cbc9ceda668e5b727f0c3a5789)
built with `-DCMAKE_INSTALL_BINDIR=/bin -DCMAKE_INSTALL_PREFIX="/usr"`

````Hack
Scanning dependencies of target test_invocation
FAIL: Fish executable not found at '../test/root/bin/fish'
make[3]: *** [CMakeFiles/test_invocation.dir/build.make:57: CMakeFiles/test_invocation] Error 1
make[2]: *** [CMakeFiles/Makefile2:835: CMakeFiles/test_invocation.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:772: CMakeFiles/test.dir/rule] Error 2
make: *** [Makefile:411: test] Error 2
````

The reason is that `../test/root` points to /usr part, which is a prefix.
but since user can override bindir, binary is installed outside of prefix and test breaks.

`root -> /home/ya/dev/random/fish/fish-shell/build/test/buildroot//usr/`

and /buildroot/bin/fish cannot be found.

steps to reproduce
- `mkdir build`
- `cd build`
- `cmake -DCMAKE_INSTALL_BINDIR=/bin -DCMAKE_INSTALL_PREFIX=/usr ..`
- `make test`

**Comment by gyakovlev** [comment]
friendly bump, seems 3.0 is close.

I patched cmakefile for gentoo for 3.0_beta1
```bash
sed -i 's#${TEST_INSTALL_DIR}/${CMAKE_INSTALL_PREFIX}#${TEST_INSTALL_DIR}#' \
                cmake/Tests.cmake
```
it just removes reference to prefix.

https://github.com/fish-shell/fish-shell/blob/40de04cc6cf2fc6b71ddd58cc60cbc5ec1c00578/cmake/Tests.cmake#L51-L53

but of course it won't work for you, because of travis and other prefixed installs.

**Comment by faho** [comment]
Yeah these have been entirely rewritten. This should work now.

**Comment by gyakovlev** [comment]
@faho still fails in a similar way
the case where the `CMAKE_INSTALL_BINDIR` is outside of `CMAKE_INSTALL_PREFIX` triggers it.

```shell-session
/bin/sh: /var/tmp/portage/app-shells/fish-9999/work/fish-9999_build/test/root/bin/fish: Not a directory
```

we do it because we want to install fish as `/bin/fish`, with the rest in `/usr`
I probably can leave workaround in place or just manually move files to `/bin` after cmake installs files to `/usr/bin`

but this bug is still valid, if it's considered a bug.

**Comment by faho** [comment]
Wait, where exactly is that /bin/sh invocation?

>we do it because we want to install fish as /bin/fish, with the rest in /usr

So you want the fish executable in /bin, with the fish functions and such in /usr/? What's that supposed to accomplish?

**Comment by krobelus** [comment]
fish has to know where to find its `share` folder or else basic functionality will break.
If the fish executable is installed as `/some-prefix/bin/fish` then `/some-prefix/share/fish` is used, see [fish.cpp#L178-L181](https://github.com/fish-shell/fish-shell/blob/master/src/fish.cpp#L178-L181).

Can you use a symlink?

**Comment by gyakovlev** [comment]
> Wait, where exactly is that /bin/sh invocation?

I'll try to dig a bit more details with new tests.

> 
> So you want the fish executable in /bin, with the fish functions and such in /usr/? What's that supposed to accomplish?

basically backwards-compat. it was historically installed like that and our /etc/shells file lists it like that. don't ask me whu.
suddenly changing all that is rather problematic (we carry multiple versions and even still have autotools-built 2.x ) and may break users.

**Comment by gyakovlev** [comment]
> fish has to know where to find its `share` folder or else basic functionality will break.
> If the fish executable is installed as `/some-prefix/bin/fish` then `/some-prefix/share/fish` is used, see [fish.cpp#L178-L181](https://github.com/fish-shell/fish-shell/blob/master/src/fish.cpp#L178-L181).
> 
> Can you use a symlink?

fish itself works fine. it's just the test invocation is broken with described configuration.

**Comment by gyakovlev** [comment]
> Wait, where exactly is that /bin/sh invocation?
> 

```shell-session
Encountered 0 errors in low-level tests                                                                  
[7/10] cd /var/tmp/portage/app-shells/fish-9999/work/fish-9999_build && /usr/bin/cmake -E remove_directory /var/tmp/portage/app-shells/fish-9999/work/fish-9999_build/test/data && /usr/bin/cmake -E remove_directo
ry /var/tmp/portage/app-shells/fish-9999/work/fish-9999_build/test/home && /usr/bin/cmake -E remove_directory /var/tmp/portage/app-shells/fish-9999/work/fish-9999_build/test/temp && /usr/bin/cmake -E make_direct
ory /var/tmp/portage/app-shells/fish-9999/work/fish-9999_build/test/data /var/tmp/portage/app-shells/fish-9999/work/fish-9999_build/test/home /var/tmp/portage/app-shells/fish-9999/work/fish-9999_build/test/temp
[8/10] cd /var/tmp/portage/app-shells/fish-9999/work/fish-9999_build && cd tests && /var/tmp/portage/app-shells/fish-9999/work/fish-9999_build/test/root/bin/fish test.fish
/bin/sh: /var/tmp/portage/app-shells/fish-9999/work/fish-9999_build/test/root/bin/fish: Not a directory  
FAILED: CMakeFiles/serial_test_fishscript                                                                
cd /var/tmp/portage/app-shells/fish-9999/work/fish-9999_build && cd tests && /var/tmp/portage/app-shells/fish-9999/work/fish-9999_build/test/root/bin/fish test.fish
ninja: build stopped: subcommand failed.
```

here's last part of build log.


and bin is not a directory even.
it's `fish_test_helper` binary

```
file    /var/tmp/portage/app-shells/fish-9999/work/fish-9999_build/test/root/bin 
/var/tmp/portage/app-shells/fish-9999/work/fish-9999_build/test/root/bin: ELF 64-bit LSB shared object, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked, interpreter /lib64/ld64.so.2, for GNU/Linux 3.10.0, with debug_info, not stripped
```

**Comment by faho** [comment]
Ah, okay, it's cmake calling a shell behind our backs.

**Comment by faho** [comment]
So it's down to some bits in cmake/Tests.cmake, in particular:

https://github.com/fish-shell/fish-shell/blob/352062219d3e612e40dfc664a5b3500108cd05c9/cmake/Tests.cmake#L38-L47

So it's

- Install fish to the CURRENT_BINARY_DIR
- Copy fish_test_helper to ${TEST_INSTALL_DIR}/${CMAKE_INSTALL_PREFIX}/bin
- Create a symlink to ${TEST_INSTALL_DIR}/${CMAKE_INSTALL_PREFIX} from ${TEST_ROOT_DIR}

Only ${TEST_INSTALL_DIR}/${CMAKE_INSTALL_PREFIX}/bin doesn't *exist*, so it calls the file "bin" instead.

`${TEST_INSTALL_DIR}` should be ${CMAKE_CURRENT_BINARY_DIR}/test/buildroot, so what is CMAKE_CURRENT_BINARY_DIR here, for you?

Also in general your cmake invocation with CMAKE_INSTALL_PREFIX and such would be nice to see.

(not that I have ever truly gotten what the various CMAKE variables are *for* anyway)

**Comment by gyakovlev** [comment]
I'll upload unexpanded (with variable names) and expanded (with values used ) cmake traces a bit later.

**Comment by faho** [comment]
Okay, without the promised traces there's really not a lot we can do here.

Closing, sorry!
