### ISSUE TITLE
git prompt causes FISH to start very slowly on OS X

### ISSUE THREAD

**Issue by duganchen** [fish-shell/fish-shell#6625]
```
dugan ) fish --version
fish, version 3.1.0
dugan ) echo $version
3.1.0
dugan ) uname -a
Darwin MacBook-Pro.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
dugan ) echo $TERM
xterm-256color-italic
dugan ) sh -c 'env HOME=$(mktemp -d) fish'
```

I had the common OS X issue where FISH would take seconds to load. It would only happen once per reboot. The first time I tried to start FISH after a reboot, it would take seconds to start. If you tried to start it again, it would start instantly. At least, until the next reboot.

I profiled it: and the cause seems to be having a prompt with VCS information in it? This absolutely jumped out at me:
```
356	7369742	--> fish_vcs_prompt
360	379	---> source /usr/local/Cellar/fish/3.1.0/share/fish/functions/fish_vcs_prompt.fish
19	19	----> function fish_vcs_prompt --description "Print the prompts for all available vcsen"
    # If a prompt succeeded, we assume that it's printed the correct info.
    # This is so we don't try svn if git already worked.
    fish_git_prompt
    or fish_hg_prompt
    or fish_svn_prompt
...
394	5204357	---> fish_git_prompt

```

I tried switching to a prompt without VCS information, and now FISH starts instantly. Even right after a reboot.

Both profile results ("FISH Profile with git prompt" and "FISH profile with minimalist prompt" are here:

https://gist.github.com/duganchen/7467164add3bcfa6cae0e2f2741ca8bc

This, more precisely, is what's taking so much time on startup:

```
277	5194027	----> set -l repo_info (command git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree HEAD 2>/dev/null)
5193750	5193750	-----> command git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree HEAD 2>/dev/null
```

And no, I'm (obviously) not in a git repository when FISH starts.

If I change fish_prompt_git to call git with its absolute path: well, that makes no difference:

```
327	4283632	----> set -l repo_info (/usr/bin/git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree HEAD 2>/dev/null)
4283305	4283305	-----> /usr/bin/git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree HEAD 2>/dev/null

```

An as for why git is so slow the first time it starts on OS X: I don't know. This takes several seconds, the first time after a reboot it runs:

```
dugan@MacBook-Pro ~ % GIT_TRACE=1 /usr/bin/git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree HEAD
15:25:54.711033 exec-cmd.c:139          trace: resolved executable path from Darwin stack: /Applications/Xcode.app/Contents/Developer/usr/bin/git
15:25:54.727587 exec-cmd.c:236          trace: resolved executable dir: /Applications/Xcode.app/Contents/Developer/usr/bin
15:25:54.739887 git.c:419               trace: built-in: git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree HEAD
fatal: not a git repository (or any of the parent directories): .git
dugan@MacBook-Pro ~ %
```

**Comment by duganchen** [comment]
It's a lot better (but not perfect) after I edit fish_git_prompt and have it launch git from its absolute path in Xcode.app:

```
277	95933	----> set -l repo_info (/Applications/Xcode.app/Contents/Developer/usr/bin/git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree HEAD 2>/dev/null)
95656	95656	-----> /Applications/Xcode.app/Contents/Developer/usr/bin/git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree HEAD 2>/dev/null

```

**Comment by duganchen** [comment]
After seeing this:

`491	4192685	---> fish_svn_prompt`

I managed to solve it.

First, I did "funced fish_vcs_prompt" and deleted the following:

```
 or fish_hg_prompt
 or fish_svn_prompt
```

I then copied /usr/local/Cellar/fish/3.1.0/share/fish/functions/fish_git_prompt.fish to ~/.config/fish/functions, and edited the copy, replacing "command git" with "/Applications/Xcode.app/Contents/Developer/usr/bin/git"

FISH now starts up instantly. Even with a VCS prompt.

**Comment by floam** [comment]
Yeah, it's the svn prompt. `xcrun` has to find the Xcode-provided tools for the full path. This is really slow the first time you run after an Xcode update (or reboot? I don't know). We could maybe figure out a hack to resolve it to the full path ourselves, else fall back to using the /usr/bin path. In my mind git and svn should both take the same amount of time, not sure why svn would be slower unless it's just ran less by a user or something.

Or maybe just disable svn by default on macOS.

**Comment by floam** [comment]
Potential hack: most people do not have homedirs that are VCS repos. On fish launch, skip doing the vcs prompt but launch no-op SVN and git commands to prime it for the next prompt.

**Comment by faho** [comment]
How about checking if the xcode path exists and using it then?

**Comment by floam** [comment]
The Xcode path is going to vary - quickly resolving it ourselves is kind of tricky. We could maybe cache it.

**Comment by faho** [comment]
>The Xcode path is going to vary

Sure about that? "/Applications/Xcode.app/Contents/Developer/usr/bin/git" looks quite stable.

**Comment by floam** [comment]
absolutely, you could install Xcode.app anywhere - and we don't know which Xcode.app is active, Xcode.app or Xcode-beta.app.

**Comment by floam** [comment]
"install" is the wrong word - you can put Xcode.app anywhere, it's portable.

**Comment by floam** [comment]
It remains to be seen if `xcode-select -p` which outputs `/Applications/Xcode-beta.app/Contents/Developer` is slow in that first run circumstance. Annoying to test.

**Comment by floam** [comment]
(The fact that the `xcrun` machinery exists for the wrappers installed to `$PATH` and `xcode-select` exists and the reason that the first run is slow is precisely because you can put Xcode anywhere and you can have multiple toolchains and versions of Xcode on a system.)

**Comment by floam** [comment]
Oh, and big one - some people do not install Xcode at all and just install the command line tools package. That might be at `/Developer` or `/Library/Developer`

**Comment by Darkshadow2** [comment]
`xcrun -f COMMAND` will give you the path to that command. You could use that to cache the path, though there'd be no way to pick up if someone uses `xcode-select` to change the Xcode being used.

**Comment by floam** [comment]
Does it short circuit caching? My concern would be if it blocks for a few second the first time you run it anyhow. I'll do some testing

**Comment by Darkshadow2** [comment]
Yeah, it blocks the first time you use it. I don't think there's any way around that using Apple's tools.

**Comment by floam** [comment]
I think there's a way around it by taking advantage of something else most likely cached and synthesizing the path.

**Comment by floam** [comment]
e.g. `xcrun -f clang | string replace -r clang git`

**Comment by Darkshadow2** [comment]
That specific case won't work, as the `clang` executable is in a different place than the `git` one.

Maybe `xcrun -f xcodebuild`?  Although I'm not sure if that's only working because it got cached earlier.

**Comment by floam** [comment]
Whoops, busted example.

**Comment by Darkshadow2** [comment]
Huh, interesting. If you give `xcrun -f` an invalid command it gives you this error:

```
xcrun: error: sh -c '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk macosx -find idonotexist 2> /dev/null' failed with exit code 17664: (null) (errno=No such file or directory)
xcrun: error: unable to find utility "idonotexist", not a developer tool or in PATH
```

So it looks like it's not even actually `xcrun` that's looking up the paths...

**Comment by floam** [comment]
Nice!

**Comment by Darkshadow2** [comment]
Ah, but if you use `xcodebuild -sdk macosx -find COMMAND` directly, there's no caching. It always takes a bit to find something.

**Comment by floam** [comment]
the dylib that causes the wrapping takes SDKROOT into account as well, so it should be possible once we have a way to quickly get the SDK path regardless of cache (`xcrun --show-sdk-path`?) we can just export something and a bare `git` or anything else should work. I think. Or maybe not.

**Comment by duganchen** [comment]
These paths aren't going to change often, so I'd propose baking the xcrun results into "set -U" universal variables instead of running xcrun on each startup.

**Comment by duganchen** [comment]
I've noticed that the [Starship prompt](https://github.com/starship/starship) doesn't have this problem.

**Comment by faho** [comment]
>I've noticed that the Starship prompt doesn't have this problem.

That's to be expected, as it doesn't actually execute the `git` binary. It instead links against libgit2, via the "git2" crate.

We don't have that luxury.

**Comment by drewish** [comment]
I've noticed another issue that seems to be slowing down the prompt is locating svn:
```
$ fish -p FILE -c 'fish_prompt'
$ sort -n FILE | tail -n 8
6655	6655	---------> read -lz key value
10674	10674	-----> command git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree HEAD 2>/dev/null
10903	10903	---------> command git diff --staged --name-status | string match -r \\w
12420	12420	---------> command git rev-list --count --left-right $upstream...HEAD 2>/dev/null
12935	12935	--------> command git symbolic-ref HEAD 2>/dev/null
18197	18197	---------> command git diff --name-status 2>/dev/null | string match -r \\w
23973	23973	---------> command git ls-files --others --exclude-standard | wc -l | string trim
594636	594636	-----> command svn info 2>/dev/null
$ svn info
svn: error: Failed to locate 'svn'.
svn: error: The subversion command line tools are no longer provided by Xcode.
$ time svn info
svn: error: Failed to locate 'svn'.
svn: error: The subversion command line tools are no longer provided by Xcode.
        1.02 real         0.35 user         0.40 sys
```

**Comment by drewish** [comment]
Oh looks like my SVN issue was fixed by https://github.com/fish-shell/fish-shell/issues/6681

**Comment by peterstory** [comment]
I think this issue can be closed, based on the fix in #6681 having been incorporated into 3.1.1 and later. Fish is speedy again! 🎉

**Comment by ridiculousfish** [comment]
Cool! Thanks!

**Comment by faho** [comment]
It's... not fixed?

The svn prompt was *one* issue, the initial problem however was that macOS does weird things with `git`, and I don't think that's changed?

I mean I'd personally be entirely okay with calling that an OS bug, but then I'm not using macOS.

**Comment by floam** [comment]
Yeah this isn't fixed.

**Comment by floam** [comment]
Update since the last time I commented here: this happens specifically after each reboot, because that clears $TMPDIR. `libxcselect.dylib` is regenerating the cache at $TMPDIR/xcrun_db.

It specifically takes so long because syspolicyd is spending a lot of time in the security framework checking code signing across the Xcode bundle.

**Comment by floam** [comment]
So there is a practical workaround: if $TMPDIR/xcrun_db doesn't exist, we run something like `git --version&` backgrounded. That'll kick off the cache being rebuilt without making block in the meantime. Likely the user won't even notice that the lack of VCS status in their prompt for those ten seconds or whatever, since most home directories are not git repos.

**Comment by floam** [comment]
I addressed this in PR #9345.

Even if fish is launched with a CWD of a git dir, the behavior is pretty pleasant with the commandline reprinting as soon as the cache file exists, so the VCS component just kind of pops in late.
