### ISSUE TITLE
trap EXIT INT does not seem to work at all with CTRL-C

### ISSUE THREAD

**Issue by netvl** [fish-shell/fish-shell#6649]
This very simple script does not print anything when I run it like `fish ./test-trap` and then press CTRL-C:

```
trap "echo After" EXIT INT
sleep 100s
```

If I run exactly the same script with bash and press CTRL-C, it prints `After` two times.

It can be reproduced with a manual `function whatever --on-event fish_exit --on-signal INT` as well.

Fish version: 3.0.2
Linux void 5.4.11-arch1-1 SMP PREEMPT Sun, 12 Jan 2020 12:15:27 +0000 x86_64 GNU/Linux

**Comment by ridiculousfish** [comment]
I can reproduce, the bash script needs to be run as a script, not directly from the command line or else you engage job control. This should work in fish, I will figure out why it doesn't.

**Comment by ridiculousfish** [comment]
In non-interactive mode, fish responds to a SIGINT-exited process by SIGINT itself. The function is enqueued but there's no place to execute it, fish is already exiting. I'll have to think about how this could work.

**Comment by scooter-dangle** [comment]
I don't know if it's relevant, but I had noticed a change in behavior of the the `--on-signal INT` flag when upgrading to 3.1 (I _think_ from 3.0, but I can at least verify the old, expected behavior on an installation of 2.7.1).

Previously, executing the following and then hitting `ctrl-c` would cause `hola` to be printed:

```fish
function stuffs --on-signal INT
    echo hola
end
```

As of 3.1.0, it doesn't.

**Comment by ridiculousfish** [comment]
Heh, yes, we enqueue the event but refuse to execute it, because we're cancelling.

**Comment by ridiculousfish** [comment]
Second issue bisects to f8ba0ac5bf4b5f27ff69ce016d072b564530a7fc.

**Comment by ridiculousfish** [comment]
It appears that non-interactive INT handlers have never worked in fish. The interactive case is a 3.1.0 regression and is fixed in bc702ccb310a92406952d515571ea30ad7c22fa4

@zanchey this would be a good addition for 3.1.1, [this comment](https://github.com/fish-shell/fish-shell/issues/6649#issuecomment-592194722) is what is fixed.

**Comment by ridiculousfish** [comment]
cherry-picked to 3.1.1 as f776c4ed881ba52ab066794ec48c8b33d62d888c

**Comment by zanchey** [comment]
Note from the original post and #6744 this appears to have been broken in 3.0.0 as well.

**Comment by zanchey** [comment]
Moving this out of the 3.1.1 milestone as the non-interactive case is still not fixed.

**Comment by Korkman** [comment]
Note that trapping SIGINT or SIGTERM should prevent the shell from performing the default action (i.e. exit). At least there should be a way to tell fish not to exit (trap function return status?)

**Comment by GReagle** [comment]
> Note that trapping SIGINT or SIGTERM should prevent the shell from performing the default action (i.e. exit). At least there should be a way to tell fish not to exit (trap function return status?)

I experimented with /bin/sh and its trap (using both bash and dash on Debian), and I notice that it does NOT prevent the shell from exiting.  Does anyone know the reason?  Here is my script:
```
#!/bin/sh
trap pwd INT
sleep 100s
```

**Comment by bakhtiyarneyman** [comment]
I would really like to see this fixed, so I posted a [bounty](https://www.bountysource.com/issues/89059193-trap-exit-int-does-not-seem-to-work-at-all-with-ctrl-c) on this bug.

**Comment by suzaku** [comment]
When I use `kill -s INT`, I can see the output. But I see nothing with `CTRL-C`, so it seems like CTRL-C's not triggering SIGINT in this case.

**Comment by bakhtiyarneyman** [comment]
@faho @ridiculousfish I see there have been some handler-related commits in the last few days. Is there a chance this issue will be fixed in the next release? I switched to fish scripts to drive various parts of my system, and this bug makes want to go back to bash. :(

**Comment by faho** [comment]
@bakhtiyarneyman It'll be worked on when it gets worked on. I have no specific plans at the moment.

**Comment by bakhtiyarneyman** [comment]
Thanks for the update.

**Comment by floam** [comment]
Huh, this actually works as expected if I attach a debugger.

**Comment by floam** [comment]
Er, you need to do a `pro hand -p true -s false SIGINT` in lldb to get the signal passed like normal.

**Comment by ridiculousfish** [comment]
Fixed in cf2ca56e3440e398e299dd9fbf8e2aa58823915bf

**Comment by ridiculousfish** [comment]
@bakhtiyarneyman I appreciate your offering a bounty but it is not necessary, please keep your money or donate it to a worthy cause. Thank you!

**Comment by ysooqe** [comment]
On 3.5.1, the fix does not seem to work for custom fish-functions (defined in `~/.config/fish/functions/`).

Example:
test_sigint.fish
```
function test_sigint
    function on_sigint --on-signal SIGINT
        echo "received SIGINT"
    end
    sleep 20
end
```
Calling `test_sigint` from the command line and doing a CTRL-C will not print out the expected "received SIGINT" line.

It does work though if I define a simple script with the exact same `test_sigint` definition inside and then calling it immediately. Doing a CTRL-C will then result in an expected "received SIGINT".

Is it expected that this does not work for custom fish-functions? If so, what would be the proper workaround to use SIGINT with those?

**Comment by pxeemo** [comment]
The same issue exists in fish 4.0.8 with trap in functions:
```fish
function test_trap
    trap 'echo Exiting normally!' EXIT
    trap 'echo Interrupted!' INT
    echo "Running... (Press Ctrl+C or wait)"
    sleep 5
end
```
neither EXIT or INT (with ctrl-c) works in this example
