### ISSUE TITLE
`exit` inside fish_prompt function doesn't exit immediately

### ISSUE THREAD

**Issue by rnhmjoj** [fish-shell/fish-shell#8033]
### Issue description

When the `exit` command is executed inside `fish_prompt`, the shell doesn't exit unless some a command is typed and executed (pressing `enter` alone doesn't work).

### Steps to reproduce:
set config.sh to
```
function fish_prompt
  echo '$ '
  exit
end
```
run `fish` and notice it doesn't exit.

### Commit that introduced the issue

b0182183d42b44dd007a63a7c4e8a0e9e9a0e24c (Rework exit command)

**Comment by rnhmjoj** [comment]
I'm doing so because I have a "launcher" mode where the shell exits after executing a single command.

**Comment by faho** [comment]
>I'm doing so because I have a "launcher" mode where the shell exits after executing a single command.

That's what `fish -c 'command'` is for.

**Comment by zanchey** [comment]
The current behaviour is interestingly broken, though, and I think should be fixed.

**Comment by rnhmjoj** [comment]
> That's what fish -c 'command' is for.

I mean I'm using the shell as a launcher, so I need interactivity. It's like a shell session but it closes before drawing the prompt a second time.

**Comment by faho** [comment]
>I mean I'm using the shell as a launcher, so I need interactivity.

That's

```fish
fish -c 'read -P "PROMPT " --shell -l command; eval $command'
```

**Comment by rnhmjoj** [comment]
Thank you, I didn't know about `read --shell`. This solves my problem, the bug is still relevant, though.

**Comment by ridiculousfish** [comment]
Fixed in ba2e7db7e85961826da6e58d897e9903c3348e29. Neat find.
