### ISSUE TITLE
Fish is running some git command each prompt

### ISSUE THREAD

**Issue by InvisOn** [fish-shell/fish-shell#8105]
I get the following message with every prompt not matter what command I run:

```
fatal: not a git repository (or any of the parent directories): .git
name@pc ~ $ 
fatal: not a git repository (or any of the parent directories): .git
name@pc ~ $
fatal: not a git repository (or any of the parent directories): .git
name@pc ~ $ bash
(default) name@pc:~ $
(default) name@pc:~ $
(default) name@pc:~ $
```
It started happening after the latest Fish update.

Fish version 3.3.0

Linux 5.8.0-59-generic #66~20.04.1-Ubuntu SMP x86_64 x86_64 x86_64 GNU/Linux

It happens with default Ubuntu terminal, Terminator 1.91, and Alacritty 0.8.0-dev (17923ef).
I have not tested any other terminals.

When testing with `sh -c 'env HOME=$(mktemp -d) fish'` the behavior went away.

**Comment by faho** [comment]
The typical git things that fish executes are for the `fish_git_prompt`, to display the git status. Often this is called via `fish_vcs_prompt` that also displays the mercurial status.

However, fish_git_prompt starts with:

https://github.com/fish-shell/fish-shell/blob/768a9b1fd391fd52dfe29269a5bad6a292b38038/share/functions/fish_git_prompt.fish#L173-L178

So it checks if 1. git is available, 2. there is a repo, and aborts otherwise, with stderr silenced so it won't print this meesage.

I would check your prompt for anything that does a git display, maybe you have your own and neglected to add a `2>/dev/null` somewhere. Or you modified `fish_git_prompt`.

You can see if it comes from the prompt by runnning `fish_prompt` and seeing if that triggers the error.

If it does, try running it with `$fish_trace` set to 1:

```fish
fish_trace=1 fish_prompt
```

This will show you what it ends up calling, and should show some `git` call somewhere.

(note to others: This is another case for $fish_trace tracing event handlers - you currently still need to narrow it down to which one is doing it)

**Comment by martinrodriguez-sf** [comment]
I am having the same issue after updating to version `3.3.0-1`.
This is the output of `fish_trace=1 fish_prompt`

```
 ~ ❯❯❯ fish_trace=1 fish_prompt
---> set -l last_status 0
----> set_color -o cyan
---> set -l cyan \e\[1m\e\[36m
----> set_color -o yellow
---> set -l yellow \e\[1m\e\[33m
----> set_color -o red
---> set -g red \e\[1m\e\[31m
----> set_color -o blue
---> set -g blue \e\[1m\e\[34m
----> set_color -o green
---> set -l green \e\[1m\e\[32m
----> set_color normal
---> set -g normal \e\(B\e\[m
----> _git_ahead
-------> git rev-list --left-right '@{upstream}...HEAD' ^/dev/null
fatal: not a git repository (or any of the parent directories): .git
------> set -l commits
------> if
------> '[' 128 != 0 ']'
-------> return
------> end if
---> set -l ahead
---> set -g whitespace ' '
---> if
---> test 0 = 0
----> set initial_indicator \e\[1m\e\[32m◆
----> set status_indicator \e\(B\e\[m❯\e\[1m\e\[36m❯\e\[1m\e\[32m❯
---> end if
-----> prompt_pwd
-------> set -l options h/help
-------> argparse -n prompt_pwd --max-args=0 h/help --
-------> if
-------> set -q _flag_help
-------> end if
-------> set -q fish_prompt_pwd_dir_length
-------> set -l fish_prompt_pwd_dir_length 1
-------> set -l realhome /home/martin
--------> string replace -r '^/home/martin($|/)' '~$1' /home/martin
-------> set -l tmp '~'
-------> if
-------> '[' 1 -eq 0 ']'
-------> else
--------> string replace -ar \(\\.\?\[^/\]\{1\}\)\[^/\]\*/ '$1/' '~'
-------> end if
----> basename '~'
---> set -l cwd \e\[1m\e\[36m\~
---> if
----> _git_branch_name
-------> git symbolic-ref HEAD ^/dev/null
-------> sed -e 's|^refs/heads/||'
fatal: not a git repository (or any of the parent directories): .git
------> echo
---> '[' '' ']'
---> end if
---> if
---> '[' 2 -gt 300000 ']'
---> end if
---> echo -n -s \e\[1m\e\[32m◆ ' ' \e\[1m\e\[36m\~ ' ' \e\(B\e\[m❯\e\[1m\e\[36m❯\e\[1m\e\[32m❯ ' '
 ~ ❯❯❯ ⏎
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
~ ❯❯❯ fish_git_prompt
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
```

And this is the output of `fish_trace=1 fish_git_prompt`:

```
~ ❯❯❯ fish_trace=1 fish_git_prompt
---> if
---> command -sq git
---> end if
----> git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree HEAD
---> set -l repo_info
---> test -n ''
---> return
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by faho** [comment]
@martinrodriguez-sf That looks like oh-my-fish stuff, `_git_ahead` isn't one of ours.

And the cause is obvious:

```fish
git rev-list --left-right '@{upstream}...HEAD' ^/dev/null
```

In fish 3.3.0, the long deprecated `^` redirection was turned off by default, so this no longer silences stderr.

Complain to whatever plugin you got that from, they haven't updated their stuff in 2.5 years. In the meantime, reenable `^` with `set -U fish_features no-stderr-nocaret`.

**Comment by martinrodriguez-sf** [comment]
Thanks!
Removing `fish-spec` package did the trick.
I am good closing this one but it was not opened by me.

**Comment by zanchey** [comment]
@InvisOn I take it reenabling the feature flag worked for you?

**Comment by Njke** [comment]
@faho Thank you so much, indeed in my custom prompt I've used error redirection with caret and I missed this deprecation from the changelog:
> Redirection to standard error with the `^` character has been disabled by default. It can be turned back on using the `stderr-nocaret` feature flag, but will eventually be disabled completely (#7105).

Replacing `^` with `2>` solved it. 🎉

---

For searchability: If you encounter these errors in prompt after updating fish shell to 3.3.0:
```sh
fatal: not a git repository (or any of the parent directories): .git
fatal: Refusing to point HEAD outside of refs/
```
Then probably you have error redirection with caret (`^`) in your prompt.
Replace it with `2>`.

**Comment by faho** [comment]
> Removing fish-spec package did the trick.

Note: fish-spec in particular was [fixed in OMF 3 years ago](https://github.com/oh-my-fish/oh-my-fish/commit/a6a67be60b1f1a4d305775847b81a5cc7d0c2f9e) (i.e. before this was ever deprecated in a release!), so if anyone else has this issue and has OMF installed... try updating that?

**Comment by Brottweiler** [comment]
Is this related? I get this message while going into a Git folder:
```
awk: cmd. line:4: fatal: cannot open file `^/dev/null' for reading: No such file or directory
```
My prompt has some git stuff, and this is the prompt I use https://github.com/Brottweiler/fishface/blob/dirty-git/functions/fish_prompt.fish
I did however test to remove all the git related things from the config but I still get the error. The prompt doesn't use awk, though, and the script seems fine to me.

**Comment by faho** [comment]
@Brottweiler 

>My prompt has some git stuff, and this is the prompt I use

That just means it's not in your prompt. It's in something else you installed. This is *not* specific to prompts. It's a general thing that the syntax has been deactivated (after being deprecated for a whole while) and needs to be replaced.

I suggest:

1. Updating all plugins you have, they very well might already be fixed
2. Doing a full `grep -r '\^/' ~/.config/fish/` and fixing everything that comes up
3. Complaining to the author of every plugin that comes up

**Comment by Brottweiler** [comment]
> 1. Updating all plugins you have, they very well might already be fixed
> 2. Doing a full `grep -r '\^[/&]' ~/.config/fish/` and fixing everything that comes up (that isn't already quoted)
> 3. Complaining to the author of every plugin that comes up

Awesome, I ran that command and found the culprit, it was https://github.com/sjl/z-fish. Thanks for clarifying and sorry for the confusion!

**Comment by faho** [comment]
Okay, question has been answered, original poster hasn't reacted in a week, closing.
