### ISSUE TITLE
kde wont load

### ISSUE THREAD

**Issue by DiarrheaMcgee** [fish-shell/fish-shell#9205]
fish 3.5.1
Linux diarrhea-factory 5.19.6-artix1-1 #1 SMP PREEMPT_DYNAMIC Thu, 01 Sep 2022 20:00:32 +0000 x86_64 GNU/Linux
xterm-kitty
plasmashell 5.25.5 kde frameworks 5.98.0 qt 5.15.6

whenever i log in at the sddm prompt it wont load kde until i open a tty and set the default shell for the user to /bin/bash
im thinking this might be a problem with ```#!/bin/sh```
also is there a bash syntax variant of fish

**Comment by faho** [comment]
Typically this happens because fish loads its configuration files and those have something weird in them. Try clearing your config.fish - this is what the issue template asks you for.

>im thinking this might be a problem with #!/bin/sh

It's not, because fish isn't /bin/sh.

>also is there a bash syntax variant of fish

No. The very idea of fish is to make a shell that's not posix-compatible. If you require posix compatibility use something else.

**Comment by DiarrheaMcgee** [comment]
i thought ```#!/bin/sh``` points to the default shell

**Comment by faho** [comment]
Because we believe posix syntax is in many ways, bad and confusing, overusing sigils to make it easy to write unreadable code, and making it easy to write code that breaks in some circumstances (e.g. filenames with spaces).

**Comment by DiarrheaMcgee** [comment]
i cleared the configuration file and it still has the same problem

**Comment by faho** [comment]
In that case, we'll require more information:

1. Do you have snapd installed? This had some breakage with KDE in the past, see #8741 - they set $XDG_DATA_DIRS to a broken value, and do it in a way that it stays around for everything. This was fixed in Ubuntu, I am unsure if it was fixed upstream or you have an outdated version (it is an aur package)
2. What else do you have in your vendor configuration? `ls /usr/share/fish/vendor_conf.d/; cat /usr/share/fish/vendor_conf.d/*` should display it.
3. What do the logs say? `cat /var/log/Xorg.0.log` if you're on xorg, I'm not sure how to get the wayland settings

**Comment by DiarrheaMcgee** [comment]
snapd is not installed 

$XDG_DATA_DIRS is ```/home/diarrhea/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share```


```ls /usr/share/fish/vendor_conf.d/; cat /usr/share/fish/vendor_conf.d/*``` output
```flatpak.fish  perlbin.fish
if type -q flatpak
    # Set XDG_DATA_DIRS to include Flatpak installations

    set -x --path XDG_DATA_DIRS

    set -q XDG_DATA_DIRS[1]; or set XDG_DATA_DIRS /usr/local/share /usr/share
    set -q XDG_DATA_HOME; or set -l XDG_DATA_HOME $HOME/.local/share

    set -l installations $XDG_DATA_HOME/flatpak
    begin
        set -le G_MESSAGES_DEBUG
        set -lx GIO_USE_VFS local
        set installations $installations (flatpak --installations)
    end

    set XDG_DATA_DIRS {$installations}/exports/share $XDG_DATA_DIRS
end
# Set path to perl scriptdirs if they exist
# https://wiki.archlinux.org/index.php/Perl_Policy#Binaries_and_scripts

if status --is-login
    for perldir in /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl
        if test -d $perldir; and not contains $perldir $PATH
            set PATH $PATH $perldir
        end
    end
end```

/var/log/Xorg.0.log.old (because the latest log is from when it worked)
```[     7.120] (--) Log file renamed from "/var/log/Xorg.pid-2902.log" to "/var/log/Xorg.0.log"
[     7.121] 
X.Org X Server 1.21.1.4
X Protocol Version 11, Revision 0
[     7.121] Current Operating System: Linux diarrhea-factory 5.19.6-artix1-1 #1 SMP PREEMPT_DYNAMIC Thu, 01 Sep 2022 20:00:32 +0000 x86_64
[     7.121] Kernel command line: BOOT_IMAGE=/vmlinuz-linux root=PARTUUID=7b9aa4da-6961-de42-bb7c-85c6b5009956 rw loglevel=3 quiet amdgpu.ppfeaturemask=0xffffffff
[     7.121]  
[     7.121] Current version of pixman: 0.40.0
[     7.121] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[     7.121] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[     7.121] (==) Log file: "/var/log/Xorg.0.log", Time: Mon Sep 12 15:40:28 2022
[     7.122] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[     7.122] (==) No Layout section.  Using the first Screen section.
[     7.122] (==) No screen section available. Using defaults.
[     7.122] (**) |-->Screen "Default Screen Section" (0)
[     7.122] (**) |   |-->Monitor "<default monitor>"
[     7.122] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[     7.122] (==) Automatically adding devices
[     7.122] (==) Automatically enabling devices
[     7.122] (==) Automatically adding GPU devices
[     7.122] (==) Automatically binding GPU devices
[     7.122] (==) Max clients allowed: 256, resource mask: 0x1fffff
[     7.122] (WW) The directory "/usr/share/fonts/misc" does not exist.
[     7.122] 	Entry deleted from font path.
[     7.122] (WW) `fonts.dir' not found (or not valid) in "/usr/share/fonts/TTF".
[     7.122] 	Entry deleted from font path.
[     7.122] 	(Run 'mkfontdir' on "/usr/share/fonts/TTF").
[     7.122] (WW) The directory "/usr/share/fonts/OTF" does not exist.
[     7.122] 	Entry deleted from font path.
[     7.122] (WW) The directory "/usr/share/fonts/Type1" does not exist.
[     7.122] 	Entry deleted from font path.
[     7.122] (WW) The directory "/usr/share/fonts/100dpi" does not exist.
[     7.122] 	Entry deleted from font path.
[     7.122] (WW) The directory "/usr/share/fonts/75dpi" does not exist.
[     7.122] 	Entry deleted from font path.
[     7.122] (==) FontPath set to:
	
[     7.122] (==) ModulePath set to "/usr/lib/xorg/modules"
[     7.122] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[     7.122] (II) Module ABI versions:
[     7.122] 	X.Org ANSI C Emulation: 0.4
[     7.122] 	X.Org Video Driver: 25.2
[     7.122] 	X.Org XInput driver : 24.4
[     7.122] 	X.Org Server Extension : 10.0
[     7.122] (++) using VT number 7

[     7.122] (II) systemd-logind: logind integration requires -keeptty and -keeptty was not provided, disabling logind integration
[     7.123] (II) xfree86: Adding drm device (/dev/dri/card0)
[     7.123] (II) Platform probe for /sys/devices/pci0000:00/0000:00:03.1/0000:0a:00.0/0000:0b:00.0/0000:0c:00.0/drm/card0
[     7.134] (--) PCI:*(12@0:0:0) 1002:73af:1458:2333 rev 192, Mem @ 0xd0000000/268435456, 0xe0000000/2097152, 0xfcc00000/1048576, I/O @ 0x0000f000/256, BIOS @ 0x????????/131072
[     7.134] (WW) Open ACPI failed (/var/run/acpid.socket) (No such file or directory)
[     7.136] (II) LoadModule: "glx"
[     7.136] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[     7.142] (II) Module glx: vendor="X.Org Foundation"
[     7.142] 	compiled for 1.21.1.4, module version = 1.0.0
[     7.142] 	ABI class: X.Org Server Extension, version 10.0
[     7.142] (II) Applying OutputClass "AMDgpu" to /dev/dri/card0
[     7.142] 	loading driver: amdgpu
[     7.142] (==) Matched amdgpu as autoconfigured driver 0
[     7.142] (==) Matched ati as autoconfigured driver 1
[     7.142] (==) Matched modesetting as autoconfigured driver 2
[     7.142] (==) Matched fbdev as autoconfigured driver 3
[     7.142] (==) Matched vesa as autoconfigured driver 4
[     7.142] (==) Assigned the driver to the xf86ConfigLayout
[     7.142] (II) LoadModule: "amdgpu"
[     7.142] (II) Loading /usr/lib/xorg/modules/drivers/amdgpu_drv.so
[     7.146] (II) Module amdgpu: vendor="X.Org Foundation"
[     7.146] 	compiled for 1.21.1.3, module version = 22.0.0
[     7.146] 	Module class: X.Org Video Driver
[     7.146] 	ABI class: X.Org Video Driver, version 25.2
[     7.146] (II) LoadModule: "ati"
[     7.146] (II) Loading /usr/lib/xorg/modules/drivers/ati_drv.so
[     7.147] (II) Module ati: vendor="X.Org Foundation"
[     7.147] 	compiled for 1.21.1.4, module version = 19.1.0
[     7.147] 	Module class: X.Org Video Driver
[     7.147] 	ABI class: X.Org Video Driver, version 25.2
[     7.156] (II) LoadModule: "radeon"
[     7.156] (II) Loading /usr/lib/xorg/modules/drivers/radeon_drv.so
[     7.159] (II) Module radeon: vendor="X.Org Foundation"
[     7.159] 	compiled for 1.21.1.4, module version = 19.1.0
[     7.159] 	Module class: X.Org Video Driver
[     7.159] 	ABI class: X.Org Video Driver, version 25.2
[     7.159] (II) LoadModule: "modesetting"
[     7.159] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[     7.159] (II) Module modesetting: vendor="X.Org Foundation"
[     7.159] 	compiled for 1.21.1.4, module version = 1.21.1
[     7.159] 	Module class: X.Org Video Driver
[     7.159] 	ABI class: X.Org Video Driver, version 25.2
[     7.159] (II) LoadModule: "fbdev"
[     7.159] (WW) Warning, couldn't open module fbdev
[     7.159] (EE) Failed to load module "fbdev" (module does not exist, 0)
[     7.159] (II) LoadModule: "vesa"
[     7.159] (WW) Warning, couldn't open module vesa
[     7.159] (EE) Failed to load module "vesa" (module does not exist, 0)
[     7.159] (II) AMDGPU: Driver for AMD Radeon:
	All GPUs supported by the amdgpu kernel driver
[     7.159] (II) RADEON: Driver for ATI/AMD Radeon chipsets:
(i cut out some of the driver loading)
	ARUBA, TAHITI, PITCAIRN, VERDE, OLAND, HAINAN, BONAIRE, KABINI,
	MULLINS, KAVERI, HAWAII
[     7.160] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[     7.165] (WW) Falling back to old probe method for modesetting
[     7.165] (II) AMDGPU(0): Creating default Display subsection in Screen section
	"Default Screen Section" for depth/fbbpp 24/32
[     7.165] (==) AMDGPU(0): Depth 24, (--) framebuffer bpp 32
[     7.165] (II) AMDGPU(0): Pixel depth = 24 bits stored in 4 bytes (32 bpp pixmaps)
[     7.165] (==) AMDGPU(0): Default visual is TrueColor
[     7.165] (==) AMDGPU(0): RGB weight 888
[     7.165] (II) AMDGPU(0): Using 8 bits per RGB (8 bit DAC)
[     7.165] (--) AMDGPU(0): Chipset: "AMD Radeon RX 6900 XT" (ChipID = 0x73af)
[     7.165] (II) Loading sub module "fb"
[     7.165] (II) LoadModule: "fb"
[     7.165] (II) Module "fb" already built-in
[     7.165] (II) Loading sub module "dri2"
[     7.165] (II) LoadModule: "dri2"
[     7.165] (II) Module "dri2" already built-in
[     7.265] (II) Loading sub module "glamoregl"
[     7.265] (II) LoadModule: "glamoregl"
[     7.265] (II) Loading /usr/lib/xorg/modules/libglamoregl.so
[     7.268] (II) Module glamoregl: vendor="X.Org Foundation"
[     7.268] 	compiled for 1.21.1.4, module version = 1.0.1
[     7.268] 	ABI class: X.Org ANSI C Emulation, version 0.4
[     7.287] (==) AMDGPU(0): DPI set to (96, 96)
[     7.287] (==) AMDGPU(0): Using gamma correction (1.0, 1.0, 1.0)
[     7.287] (II) Loading sub module "ramdac"
[     7.287] (II) LoadModule: "ramdac"
[     7.287] (II) Module "ramdac" already built-in
[     7.287] (II) UnloadModule: "radeon"
[     7.287] (II) Unloading radeon
[     7.287] (II) UnloadModule: "modesetting"
[     7.287] (II) Unloading modesetting
[     7.287] (II) AMDGPU(0): [DRI2] Setup complete
[     7.287] (II) AMDGPU(0): [DRI2]   DRI driver: radeonsi
[     7.287] (II) AMDGPU(0): [DRI2]   VDPAU driver: radeonsi
[     7.312] (II) AMDGPU(0): Front buffer pitch: 10240 bytes
[     7.313] (II) AMDGPU(0): SYNC extension fences enabled
[     7.313] (II) AMDGPU(0): Present extension enabled
[     7.313] (==) AMDGPU(0): DRI3 enabled
[     7.313] (==) AMDGPU(0): Backing store enabled
[     7.313] (II) AMDGPU(0): Direct rendering enabled
[     7.320] (II) AMDGPU(0): Use GLAMOR acceleration.
[     7.320] (II) AMDGPU(0): Acceleration enabled
[     7.320] (==) AMDGPU(0): DPMS enabled
[     7.320] (==) AMDGPU(0): Silken mouse enabled
[     7.320] (II) AMDGPU(0): Set up textured video (glamor)
[     7.326] (II) Initializing extension Generic Event Extension
[     7.326] (II) Initializing extension SHAPE
[     7.326] (II) Initializing extension MIT-SHM
[     7.326] (II) Initializing extension XInputExtension
[     7.326] (II) Initializing extension XTEST
[     7.326] (II) Initializing extension BIG-REQUESTS
[     7.326] (II) Initializing extension SYNC
[     7.327] (II) Initializing extension XKEYBOARD
[     7.327] (II) Initializing extension XC-MISC
[     7.327] (II) Initializing extension SECURITY
[     7.327] (II) Initializing extension XFIXES
[     7.327] (II) Initializing extension RENDER
[     7.327] (II) Initializing extension RANDR
[     7.327] (II) Initializing extension COMPOSITE
[     7.327] (II) Initializing extension DAMAGE
[     7.327] (II) Initializing extension MIT-SCREEN-SAVER
[     7.327] (II) Initializing extension DOUBLE-BUFFER
[     7.327] (II) Initializing extension RECORD
[     7.327] (II) Initializing extension DPMS
[     7.327] (II) Initializing extension Present
[     7.327] (II) Initializing extension DRI3
[     7.327] (II) Initializing extension X-Resource
[     7.327] (II) Initializing extension XVideo
[     7.327] (II) Initializing extension XVideo-MotionCompensation
[     7.327] (II) Initializing extension GLX
[     7.330] (II) AIGLX: Loaded and initialized radeonsi
[     7.330] (II) GLX: Initialized DRI2 GL provider for screen 0
[     7.330] (II) Initializing extension XFree86-VidModeExtension
[     7.330] (II) Initializing extension XFree86-DGA
[     7.330] (II) Initializing extension XFree86-DRI
[     7.330] (II) Initializing extension DRI2
[     7.330] (II) AMDGPU(0): Setting screen physical size to 677 x 381
[     7.332] (EE) AMDGPU(0): Failed to make import prime FD as pixmap: 22
[     7.385] (II) config/udev: Adding input device Power Button (/dev/input/event1)
[     7.385] (**) Power Button: Applying InputClass "libinput keyboard catchall"
[     7.385] (II) LoadModule: "libinput"
[     7.385] (II) Loading /usr/lib/xorg/modules/input/libinput_drv.so
[     7.387] (II) Module libinput: vendor="X.Org Foundation"
[     7.387] 	compiled for 1.21.1.3, module version = 1.2.1
[     7.387] 	Module class: X.Org XInput Driver
[     7.387] 	ABI class: X.Org XInput driver, version 24.4
[     7.387] (II) Using input driver 'libinput' for 'Power Button'
[     7.387] (**) Power Button: always reports core events
[     7.387] (**) Option "Device" "/dev/input/event1"
[     7.389] (II) event1  - Power Button: is tagged by udev as: Keyboard
[     7.389] (II) event1  - Power Button: device is a keyboard
[     7.389] (II) event1  - Power Button: device removed
[     7.427] (**) Option "config_info" "udev:/sys/devices/LNXSYSTM:00/LNXPWRBN:00/input/input1/event1"
[     7.427] (II) XINPUT: Adding extended input device "Power Button" (type: KEYBOARD, id 6)
[     7.428] (II) event1  - Power Button: is tagged by udev as: Keyboard
[     7.428] (II) event1  - Power Button: device is a keyboard
[     7.428] (II) config/udev: Adding input device Power Button (/dev/input/event0)
[     7.428] (**) Power Button: Applying InputClass "libinput keyboard catchall"
[     7.428] (II) Using input driver 'libinput' for 'Power Button'
[     7.428] (**) Power Button: always reports core events
[     7.428] (**) Option "Device" "/dev/input/event0"
[     7.428] (II) event0  - Power Button: is tagged by udev as: Keyboard
[     7.428] (II) event0  - Power Button: device is a keyboard
[     7.428] (II) event0  - Power Button: device removed
[     7.451] (**) Option "config_info" "udev:/sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0C0C:00/input/input0/event0"
[     7.451] (II) XINPUT: Adding extended input device "Power Button" (type: KEYBOARD, id 7)
[     7.451] (II) event0  - Power Button: is tagged by udev as: Keyboard
[     7.451] (II) event0  - Power Button: device is a keyboard
[     7.452] (II) config/udev: Adding input device Glorious Model O Wireless (/dev/input/event5)
[     7.452] (**) Glorious Model O Wireless: Applying InputClass "libinput pointer catchall"
[     7.452] (II) Using input driver 'libinput' for 'Glorious Model O Wireless'
[     7.452] (**) Glorious Model O Wireless: always reports core events
[     7.452] (**) Option "Device" "/dev/input/event5"
[     7.508] (II) event5  - Glorious Model O Wireless: is tagged by udev as: Mouse
[     7.508] (II) event5  - Glorious Model O Wireless: device is a pointer
[     7.508] (II) event5  - Glorious Model O Wireless: device removed
[     7.541] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:07:00.1/usb1/1-3/1-3:1.0/0003:258A:2022.0004/input/input5/event5"
[     7.541] (II) XINPUT: Adding extended input device "Glorious Model O Wireless" (type: MOUSE, id 8)
[     7.541] (**) Option "AccelerationScheme" "none"
[     7.541] (**) Glorious Model O Wireless: (accel) selected scheme none/0
[     7.541] (**) Glorious Model O Wireless: (accel) acceleration factor: 2.000
[     7.541] (**) Glorious Model O Wireless: (accel) acceleration threshold: 4
[     7.598] (II) event5  - Glorious Model O Wireless: is tagged by udev as: Mouse
[     7.598] (II) event5  - Glorious Model O Wireless: device is a pointer
[     7.599] (II) config/udev: Adding input device Glorious Model O Wireless (/dev/input/mouse1)
[     7.599] (II) No input driver specified, ignoring this device.
[     7.599] (II) This device may have been added with another device file.
[     7.599] (II) config/udev: Adding input device Glorious Model O Wireless (/dev/input/event10)
[     7.599] (II) No input driver specified, ignoring this device.
[     7.599] (II) This device may have been added with another device file.
[     7.599] (II) config/udev: Adding input device Glorious Model O Wireless Consumer Control (/dev/input/event6)
[     7.599] (**) Glorious Model O Wireless Consumer Control: Applying InputClass "libinput keyboard catchall"
[     7.599] (II) Using input driver 'libinput' for 'Glorious Model O Wireless Consumer Control'
[     7.599] (**) Glorious Model O Wireless Consumer Control: always reports core events
[     7.599] (**) Option "Device" "/dev/input/event6"
[     7.600] (II) event6  - Glorious Model O Wireless Consumer Control: is tagged by udev as: Keyboard
[     7.600] (II) event6  - Glorious Model O Wireless Consumer Control: device is a keyboard
[     7.600] (II) event6  - Glorious Model O Wireless Consumer Control: device removed
[     7.614] (II) libinput: Glorious Model O Wireless Consumer Control: needs a virtual subdevice
[     7.614] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:07:00.1/usb1/1-3/1-3:1.1/0003:258A:2022.0005/input/input6/event6"
[     7.614] (II) XINPUT: Adding extended input device "Glorious Model O Wireless Consumer Control" (type: MOUSE, id 9)
[     7.614] (**) Option "AccelerationScheme" "none"
[     7.614] (**) Glorious Model O Wireless Consumer Control: (accel) selected scheme none/0
[     7.614] (**) Glorious Model O Wireless Consumer Control: (accel) acceleration factor: 2.000
[     7.614] (**) Glorious Model O Wireless Consumer Control: (accel) acceleration threshold: 4
[     7.615] (II) event6  - Glorious Model O Wireless Consumer Control: is tagged by udev as: Keyboard
[     7.615] (II) event6  - Glorious Model O Wireless Consumer Control: device is a keyboard
[     7.616] (II) config/udev: Adding input device Glorious Model O Wireless System Control (/dev/input/event7)
[     7.616] (**) Glorious Model O Wireless System Control: Applying InputClass "libinput keyboard catchall"
[     7.616] (II) Using input driver 'libinput' for 'Glorious Model O Wireless System Control'
[     7.616] (**) Glorious Model O Wireless System Control: always reports core events
[     7.616] (**) Option "Device" "/dev/input/event7"
[     7.616] (II) event7  - Glorious Model O Wireless System Control: is tagged by udev as: Keyboard
[     7.616] (II) event7  - Glorious Model O Wireless System Control: device is a keyboard
[     7.616] (II) event7  - Glorious Model O Wireless System Control: device removed
[     7.641] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:07:00.1/usb1/1-3/1-3:1.1/0003:258A:2022.0005/input/input7/event7"
[     7.641] (II) XINPUT: Adding extended input device "Glorious Model O Wireless System Control" (type: KEYBOARD, id 10)
[     7.642] (II) event7  - Glorious Model O Wireless System Control: is tagged by udev as: Keyboard
[     7.642] (II) event7  - Glorious Model O Wireless System Control: device is a keyboard
[     7.642] (II) config/udev: Adding input device Glorious Model O Wireless Keyboard (/dev/input/event8)
[     7.642] (**) Glorious Model O Wireless Keyboard: Applying InputClass "libinput keyboard catchall"
[     7.642] (II) Using input driver 'libinput' for 'Glorious Model O Wireless Keyboard'
[     7.642] (**) Glorious Model O Wireless Keyboard: always reports core events
[     7.642] (**) Option "Device" "/dev/input/event8"
[     7.643] (II) event8  - Glorious Model O Wireless Keyboard: is tagged by udev as: Keyboard
[     7.643] (II) event8  - Glorious Model O Wireless Keyboard: device is a keyboard
[     7.643] (II) event8  - Glorious Model O Wireless Keyboard: device removed
[     7.674] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:07:00.1/usb1/1-3/1-3:1.1/0003:258A:2022.0005/input/input8/event8"
[     7.674] (II) XINPUT: Adding extended input device "Glorious Model O Wireless Keyboard" (type: KEYBOARD, id 11)
[     7.675] (II) event8  - Glorious Model O Wireless Keyboard: is tagged by udev as: Keyboard
[     7.675] (II) event8  - Glorious Model O Wireless Keyboard: device is a keyboard
[     7.676] (II) config/udev: Adding input device Glorious Model O Wireless (/dev/input/event9)
[     7.676] (II) No input driver specified, ignoring this device.
[     7.676] (II) This device may have been added with another device file.
[     7.676] (II) config/udev: Adding input device USB PnP Audio Device (/dev/input/event17)
[     7.676] (**) USB PnP Audio Device: Applying InputClass "libinput keyboard catchall"
[     7.676] (II) Using input driver 'libinput' for 'USB PnP Audio Device'
[     7.676] (**) USB PnP Audio Device: always reports core events
[     7.676] (**) Option "Device" "/dev/input/event17"
[     7.677] (II) event17 - USB PnP Audio Device: is tagged by udev as: Keyboard
[     7.677] (II) event17 - USB PnP Audio Device: device is a keyboard
[     7.677] (II) event17 - USB PnP Audio Device: device removed
[     7.711] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:07:00.3/usb3/3-2/3-2.4/3-2.4:1.2/0003:0C76:161E.0007/input/input17/event17"
[     7.711] (II) XINPUT: Adding extended input device "USB PnP Audio Device" (type: KEYBOARD, id 12)
[     7.712] (II) event17 - USB PnP Audio Device: is tagged by udev as: Keyboard
[     7.712] (II) event17 - USB PnP Audio Device: device is a keyboard
[     7.712] (II) config/udev: Adding input device HDA ATI HDMI HDMI/DP,pcm=3 (/dev/input/event11)
[     7.712] (II) No input driver specified, ignoring this device.
[     7.712] (II) This device may have been added with another device file.
[     7.712] (II) config/udev: Adding input device HDA ATI HDMI HDMI/DP,pcm=7 (/dev/input/event12)
[     7.712] (II) No input driver specified, ignoring this device.
[     7.712] (II) This device may have been added with another device file.
[     7.712] (II) config/udev: Adding input device HDA ATI HDMI HDMI/DP,pcm=8 (/dev/input/event13)
[     7.712] (II) No input driver specified, ignoring this device.
[     7.712] (II) This device may have been added with another device file.
[     7.712] (II) config/udev: Adding input device HDA ATI HDMI HDMI/DP,pcm=9 (/dev/input/event14)
[     7.712] (II) No input driver specified, ignoring this device.
[     7.712] (II) This device may have been added with another device file.
[     7.713] (II) config/udev: Adding input device HDA ATI HDMI HDMI/DP,pcm=10 (/dev/input/event15)
[     7.713] (II) No input driver specified, ignoring this device.
[     7.713] (II) This device may have been added with another device file.
[     7.713] (II) config/udev: Adding input device HDA ATI HDMI HDMI/DP,pcm=11 (/dev/input/event16)
[     7.713] (II) No input driver specified, ignoring this device.
[     7.713] (II) This device may have been added with another device file.
[     7.713] (II) config/udev: Adding input device Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard (/dev/input/event3)
[     7.713] (**) Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard: Applying InputClass "libinput keyboard catchall"
[     7.713] (II) Using input driver 'libinput' for 'Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard'
[     7.713] (**) Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard: always reports core events
[     7.713] (**) Option "Device" "/dev/input/event3"
[     7.713] (II) event3  - Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard: is tagged by udev as: Keyboard
[     7.714] (II) event3  - Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard: device is a keyboard
[     7.714] (II) event3  - Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard: device removed
[     7.727] (II) libinput: Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard: needs a virtual subdevice
[     7.727] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:08.1/0000:0e:00.3/usb5/5-4/5-4:1.0/0003:1B1C:1B7D.0001/input/input3/event3"
[     7.727] (II) XINPUT: Adding extended input device "Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard" (type: MOUSE, id 13)
[     7.728] (**) Option "AccelerationScheme" "none"
[     7.728] (**) Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard: (accel) selected scheme none/0
[     7.728] (**) Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard: (accel) acceleration factor: 2.000
[     7.728] (**) Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard: (accel) acceleration threshold: 4
[     7.728] (II) event3  - Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard: is tagged by udev as: Keyboard
[     7.728] (II) event3  - Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard: device is a keyboard
[     7.729] (II) config/udev: Adding input device Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse (/dev/input/event4)
[     7.729] (**) Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse: Applying InputClass "libinput pointer catchall"
[     7.729] (II) Using input driver 'libinput' for 'Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse'
[     7.729] (**) Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse: always reports core events
[     7.729] (**) Option "Device" "/dev/input/event4"
[     7.729] (II) event4  - Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse: is tagged by udev as: Mouse
[     7.729] (II) event4  - Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse: device is a pointer
[     7.729] (II) event4  - Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse: device removed
[     7.761] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:08.1/0000:0e:00.3/usb5/5-4/5-4:1.0/0003:1B1C:1B7D.0001/input/input4/event4"
[     7.761] (II) XINPUT: Adding extended input device "Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse" (type: MOUSE, id 14)
[     7.761] (**) Option "AccelerationScheme" "none"
[     7.761] (**) Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse: (accel) selected scheme none/0
[     7.761] (**) Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse: (accel) acceleration factor: 2.000
[     7.761] (**) Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse: (accel) acceleration threshold: 4
[     7.762] (II) event4  - Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse: is tagged by udev as: Mouse
[     7.762] (II) event4  - Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse: device is a pointer
[     7.762] (II) config/udev: Adding input device Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse (/dev/input/js0)
[     7.762] (II) No input driver specified, ignoring this device.
[     7.762] (II) This device may have been added with another device file.
[     7.762] (II) config/udev: Adding input device Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse (/dev/input/mouse0)
[     7.762] (II) No input driver specified, ignoring this device.
[     7.762] (II) This device may have been added with another device file.
[     7.762] (II) config/udev: Adding input device HD-Audio Generic Front Mic (/dev/input/event19)
[     7.762] (II) No input driver specified, ignoring this device.
[     7.763] (II) This device may have been added with another device file.
[     7.763] (II) config/udev: Adding input device HD-Audio Generic Rear Mic (/dev/input/event20)
[     7.763] (II) No input driver specified, ignoring this device.
[     7.763] (II) This device may have been added with another device file.
[     7.763] (II) config/udev: Adding input device HD-Audio Generic Line (/dev/input/event21)
[     7.763] (II) No input driver specified, ignoring this device.
[     7.763] (II) This device may have been added with another device file.
[     7.763] (II) config/udev: Adding input device HD-Audio Generic Line Out Front (/dev/input/event22)
[     7.763] (II) No input driver specified, ignoring this device.
[     7.763] (II) This device may have been added with another device file.
[     7.763] (II) config/udev: Adding input device HD-Audio Generic Line Out Surround (/dev/input/event23)
[     7.763] (II) No input driver specified, ignoring this device.
[     7.763] (II) This device may have been added with another device file.
[     7.763] (II) config/udev: Adding input device HD-Audio Generic Line Out CLFE (/dev/input/event24)
[     7.763] (II) No input driver specified, ignoring this device.
[     7.763] (II) This device may have been added with another device file.
[     7.763] (II) config/udev: Adding input device HD-Audio Generic Front Headphone (/dev/input/event25)
[     7.763] (II) No input driver specified, ignoring this device.
[     7.763] (II) This device may have been added with another device file.
[     7.763] (II) config/udev: Adding input device Eee PC WMI hotkeys (/dev/input/event18)
[     7.763] (**) Eee PC WMI hotkeys: Applying InputClass "libinput keyboard catchall"
[     7.763] (II) Using input driver 'libinput' for 'Eee PC WMI hotkeys'
[     7.763] (**) Eee PC WMI hotkeys: always reports core events
[     7.763] (**) Option "Device" "/dev/input/event18"
[     7.764] (II) event18 - Eee PC WMI hotkeys: is tagged by udev as: Keyboard
[     7.764] (II) event18 - Eee PC WMI hotkeys: device is a keyboard
[     7.764] (II) event18 - Eee PC WMI hotkeys: device removed
[     7.831] (**) Option "config_info" "udev:/sys/devices/platform/eeepc-wmi/input/input18/event18"
[     7.831] (II) XINPUT: Adding extended input device "Eee PC WMI hotkeys" (type: KEYBOARD, id 15)
[     7.831] (II) event18 - Eee PC WMI hotkeys: is tagged by udev as: Keyboard
[     7.831] (II) event18 - Eee PC WMI hotkeys: device is a keyboard
[     7.832] (II) config/udev: Adding input device PC Speaker (/dev/input/event2)
[     7.832] (II) No input driver specified, ignoring this device.
[     7.832] (II) This device may have been added with another device file.
[     7.835] (**) Glorious Model O Wireless Consumer Control: Applying InputClass "libinput keyboard catchall"
[     7.835] (II) Using input driver 'libinput' for 'Glorious Model O Wireless Consumer Control'
[     7.835] (**) Glorious Model O Wireless Consumer Control: always reports core events
[     7.835] (**) Option "Device" "/dev/input/event6"
[     7.835] (II) libinput: Glorious Model O Wireless Consumer Control: is a virtual subdevice
[     7.835] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:01.2/0000:02:00.0/0000:03:08.0/0000:07:00.1/usb1/1-3/1-3:1.1/0003:258A:2022.0005/input/input6/event6"
[     7.835] (II) XINPUT: Adding extended input device "Glorious Model O Wireless Consumer Control" (type: KEYBOARD, id 16)
[     7.835] (**) Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard: Applying InputClass "libinput keyboard catchall"
[     7.835] (II) Using input driver 'libinput' for 'Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard'
[     7.835] (**) Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard: always reports core events
[     7.835] (**) Option "Device" "/dev/input/event3"
[     7.835] (II) libinput: Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard: is a virtual subdevice
[     7.835] (**) Option "config_info" "udev:/sys/devices/pci0000:00/0000:00:08.1/0000:0e:00.3/usb5/5-4/5-4:1.0/0003:1B1C:1B7D.0001/input/input3/event3"
[     7.835] (II) XINPUT: Adding extended input device "Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard" (type: KEYBOARD, id 17)
[     9.759] (II) event1  - Power Button: device removed
[     9.784] (II) event0  - Power Button: device removed
[     9.801] (II) event5  - Glorious Model O Wireless: device removed
[     9.844] (II) event7  - Glorious Model O Wireless System Control: device removed
[     9.861] (II) event8  - Glorious Model O Wireless Keyboard: device removed
[     9.904] (II) event17 - USB PnP Audio Device: device removed
[     9.938] (II) event4  - Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard Mouse: device removed
[     9.971] (II) event18 - Eee PC WMI hotkeys: device removed
[    10.034] (II) event6  - Glorious Model O Wireless Consumer Control: device removed
[    10.051] (II) event3  - Corsair CORSAIR K100 RGB Mechanical Gaming Keyboard: device removed
[    10.067] (II) AIGLX: Suspending AIGLX clients for VT switch
[   361.671] (II) UnloadModule: "libinput"
[   361.671] (II) UnloadModule: "libinput"
[   361.671] (II) UnloadModule: "libinput"
[   361.671] (II) UnloadModule: "libinput"
[   361.671] (II) UnloadModule: "libinput"
[   361.671] (II) UnloadModule: "libinput"
[   361.671] (II) UnloadModule: "libinput"
[   361.671] (II) UnloadModule: "libinput"
[   361.671] (II) UnloadModule: "libinput"
[   361.671] (II) UnloadModule: "libinput"
[   361.671] (II) UnloadModule: "libinput"
[   361.671] (II) UnloadModule: "libinput"
[   361.672] (II) Server terminated successfully (0). Closing log file.```

**Comment by faho** [comment]
Okay, there's nothing out of the ordinary there and I have those same vendor config files, and I'm also using KDE on arch with sddm.

So it's either something still leftover from your config (including universal variables), some admin config in /etc or something entirely different.

Please do:

- Move the entirety of ~/.config/fish out of the way - `mv ~/.config/fish ~/.config/fishbak`
- Show your universal variables with `set -S (set -Un)`
- Show your admin-level fish config with `cat /etc/fish/**.fish`
- Run a non-working session and then check the output of `journalctl --user -b` - this should show the logs for the user's systemd session which should capture the KDE stuff from the current boot

**Comment by DiarrheaMcgee** [comment]
i got the output of all the commands but then github deleted it

universal variables:
```$PATH: set in global scope, exported, a path variable with 14 elements
$PATH[1]: |/home/diarrhea/.emacs.d/bin|
$PATH[2]: |/home/diarrhea/.config/lemonbar|
$PATH[3]: |$PATH|
$PATH[4]: |/opt/rocm/bin/|
$PATH[5]: |/usr/local/sbin|
$PATH[6]: |/usr/local/bin|
$PATH[7]: |/usr/bin|
$PATH[8]: |/var/lib/flatpak/exports/bin|
$PATH[9]: |/usr/lib/jvm/default/bin|
$PATH[10]: |/opt/rocm-5.2.3/bin|
$PATH[11]: |/opt/rocm-5.2.3/hip/bin|
$PATH[12]: |/usr/bin/site_perl|
$PATH[13]: |/usr/bin/vendor_perl|
$PATH[14]: |/usr/bin/core_perl|
$PATH: set in universal scope, unexported, a path variable with 33 elements
$PATH[1]: |/usr/local/sbin|
$PATH[2]: |~/.emacs.d/bin|
$PATH[3]: |~/GMiner|
$PATH[4]: |~/.config/lemonbar|
$PATH[5]: |~/clib|
$PATH[6]: |/usr/local/bin|
$PATH[7]: |~/.emacs.d/bin|
$PATH[8]: |~/GMiner|
$PATH[9]: |~/.config/lemonbar|
$PATH[10]: |~/clib|
$PATH[11]: |/usr/bin|
$PATH[12]: |~/.emacs.d/bin|
$PATH[13]: |~/GMiner|
$PATH[14]: |~/.config/lemonbar|
$PATH[15]: |~/clib|
$PATH[16]: |/usr/bin/site_perl|
$PATH[17]: |~/.emacs.d/bin|
$PATH[18]: |~/GMiner|
$PATH[19]: |~/.config/lemonbar|
$PATH[20]: |~/clib|
$PATH[21]: |/usr/bin/vendor_perl|
$PATH[22]: |~/.emacs.d/bin|
$PATH[23]: |~/GMiner|
$PATH[24]: |~/.config/lemonbar|
$PATH[25]: |~/clib|
$PATH[26]: |/usr/bin/core_perl|
$PATH[27]: |~/.emacs.d/bin|
$PATH[28]: |~/GMiner|
$PATH[29]: |~/.config/lemonbar|
$PATH[30]: |~/clib|
$PATH[31]: |/home/diarrhea/.emacs.d/bin|
$PATH[32]: |/home/diarrhea/GMiner|
$PATH[33]: |/home/diarrhea/.config/lemonbar|
$__fish_initialized: set in universal scope, unexported, with 1 elements
$__fish_initialized[1]: |3400|
$fish_color_autosuggestion: set in universal scope, unexported, with 2 elements
$fish_color_autosuggestion[1]: |555|
$fish_color_autosuggestion[2]: |brblack|
$fish_color_cancel: set in universal scope, unexported, with 1 elements
$fish_color_cancel[1]: |-r|
$fish_color_command: set in universal scope, unexported, with 1 elements
$fish_color_command[1]: |005fd7|
$fish_color_comment: set in universal scope, unexported, with 1 elements
$fish_color_comment[1]: |990000|
$fish_color_cwd: set in universal scope, unexported, with 1 elements
$fish_color_cwd[1]: |green|
$fish_color_cwd_root: set in universal scope, unexported, with 1 elements
$fish_color_cwd_root[1]: |red|
$fish_color_end: set in universal scope, unexported, with 1 elements
$fish_color_end[1]: |009900|
$fish_color_error: set in universal scope, unexported, with 1 elements
$fish_color_error[1]: |ff0000|
$fish_color_escape: set in universal scope, unexported, with 1 elements
$fish_color_escape[1]: |00a6b2|
$fish_color_history_current: set in universal scope, unexported, with 1 elements
$fish_color_history_current[1]: |--bold|
$fish_color_host: set in universal scope, unexported, with 1 elements
$fish_color_host[1]: |normal|
$fish_color_host_remote: set in universal scope, unexported, with 1 elements
$fish_color_host_remote[1]: |yellow|
$fish_color_normal: set in universal scope, unexported, with 1 elements
$fish_color_normal[1]: |normal|
$fish_color_operator: set in universal scope, unexported, with 1 elements
$fish_color_operator[1]: |00a6b2|
$fish_color_param: set in universal scope, unexported, with 1 elements
$fish_color_param[1]: |00afff|
$fish_color_quote: set in universal scope, unexported, with 1 elements
$fish_color_quote[1]: |999900|
$fish_color_redirection: set in universal scope, unexported, with 1 elements
$fish_color_redirection[1]: |00afff|
$fish_color_search_match: set in universal scope, unexported, with 2 elements
$fish_color_search_match[1]: |bryellow|
$fish_color_search_match[2]: |--background=brblack|
$fish_color_selection: set in universal scope, unexported, with 3 elements
$fish_color_selection[1]: |white|
$fish_color_selection[2]: |--bold|
$fish_color_selection[3]: |--background=brblack|
$fish_color_status: set in universal scope, unexported, with 1 elements
$fish_color_status[1]: |red|
$fish_color_user: set in universal scope, unexported, with 1 elements
$fish_color_user[1]: |brgreen|
$fish_color_valid_path: set in universal scope, unexported, with 1 elements
$fish_color_valid_path[1]: |--underline|
$fish_key_bindings: set in universal scope, unexported, with 1 elements
$fish_key_bindings[1]: |fish_default_key_bindings|
$fish_pager_color_completion: set in universal scope, unexported, with 0 elements
$fish_pager_color_description: set in universal scope, unexported, with 2 elements
$fish_pager_color_description[1]: |B3A06D|
$fish_pager_color_description[2]: |yellow|
$fish_pager_color_prefix: set in universal scope, unexported, with 3 elements
$fish_pager_color_prefix[1]: |normal|
$fish_pager_color_prefix[2]: |--bold|
$fish_pager_color_prefix[3]: |--underline|
$fish_pager_color_progress: set in universal scope, unexported, with 2 elements
$fish_pager_color_progress[1]: |brwhite|
$fish_pager_color_progress[2]: |--background=cyan|
$fish_pager_color_selected_background: set in universal scope, unexported, with 1 elements
$fish_pager_color_selected_background[1]: |-r|

```

the admin fish config is just the default empty thing and journalctl isnt installed because i use openrc

**Comment by DiarrheaMcgee** [comment]
i just tried rebooting and the problem still exists after moving the configuration folder

**Comment by faho** [comment]
>
$PATH: set in universal scope, unexported, a path variable with 33 elements
$PATH[1]: |/usr/local/sbin|
$PATH[2]: |~/.emacs.d/bin|
$PATH[3]: |~/GMiner|
$PATH[4]: |~/.config/lemonbar|
$PATH[5]: |~/clib|

Uuuuh, your $PATH is pretty broken. Run `set -eU PATH`. That should blow away the broken universal variable which might be interfering here.

And then stop setting a universal $PATH, and especially stop appending to it in config.fish.

>journalctl isnt installed because i use openrc

Afraid I can't help you with that. See if you can find the KDE session logs anywhere else.

**Comment by DiarrheaMcgee** [comment]
dont the path variables get cleared when i moved config.fish (since they were  getting declared there)
i checked ```set -S (set -Un)``` and it had the same output as before i did ```set -eU PATH```

**Comment by faho** [comment]
>didnt the path variables get cleared when i moved config.fish (since they were getting declared there)


Universal variables are persisted by fish. It stores them in ~/.config/fish/fish_variables. You would indeed have moved that aside if you did as I suggested and moved the entirety of ~/.config/fish, the entire *directory*. However, if you had a fish running that would have recreated it.

>since they were getting declared there

That's your problem. You're adding to $PATH in config.fish, but you have set $PATH to be saved automatically, and so it keeps growing. Which is how you get this mess:

```
$PATH[1]: |/usr/local/sbin|
$PATH[2]: |~/.emacs.d/bin|
$PATH[3]: |~/GMiner|
$PATH[4]: |~/.config/lemonbar|
$PATH[5]: |~/clib|
$PATH[6]: |/usr/local/bin|
$PATH[7]: |~/.emacs.d/bin|
$PATH[8]: |~/GMiner|
$PATH[9]: |~/.config/lemonbar|
$PATH[10]: |~/clib|
$PATH[11]: |/usr/bin|
$PATH[12]: |~/.emacs.d/bin|
$PATH[13]: |~/GMiner|
```

Notice how that repeats?

And then you have a global version of the variable under the universal, which has this gem:

```
$PATH[1]: |/home/diarrhea/.emacs.d/bin|
$PATH[2]: |/home/diarrhea/.config/lemonbar|
$PATH[3]: |$PATH|
$PATH[4]: |/opt/rocm/bin/|
```

See how element 3 is a literal `$PATH`? Yeah, that's just completely broken. This would be what happens if you did e.g.

```fish
set PATH ~/.emacs.d/bin '$PATH' /opt/room/bin
```

See those single-quotes? Those mean that `$PATH` isn't expanded but instead the actual literal string "$PATH".

>i checked set -S (set -Un) and it had the same output as before i did set -eU PATH

I'm fairly certain it didn't, or you didn't run the correct thing.

It's `set -eU PATH`, in that spelling, without `$`.

**Comment by faho** [comment]
Okay, no reply in a week, closing.

If you get back to us we'll reopen.

**Comment by DiarrheaMcgee** [comment]
i had to reinstall linux so the problem is gone
