### ISSUE TITLE
completions: zfs completions broken due to read-only variable

### ISSUE THREAD

**Issue by ammgws** [fish-shell/fish-shell#9705]
```sh
# fish --version
fish, version 3.6.1
# zfs load-key r[TAB]: _: cannot overwrite read-only variable
/usr/share/fish/functions/__fish_is_zfs_feature_enabled.fish (line 12): 
    echo $feature_name | read -l _ _ state _
    ^
in function '__fish_is_zfs_feature_enabled' with arguments 'feature@bookmarks'
	called on line 344 of file /usr/share/fish/completions/zfs.fish
from sourcing file /usr/share/fish/completions/zfs.fish

(Type 'help read' for related documentation)
read: _: cannot overwrite read-only variable
/usr/share/fish/functions/__fish_is_zfs_feature_enabled.fish (line 12): 
    echo $feature_name | read -l _ _ state _
    ^
in function '__fish_is_zfs_feature_enabled' with arguments 'feature@bookmarks'
	called on line 508 of file /usr/share/fish/completions/zfs.fish
from sourcing file /usr/share/fish/completions/zfs.fish

(Type 'help read' for related documentation)
read: _: cannot overwrite read-only variable
/usr/share/fish/functions/__fish_is_zfs_feature_enabled.fish (line 12): 
    echo $feature_name | read -l _ _ state _
    ^
in function '__fish_is_zfs_feature_enabled' with arguments 'feature@extensible_dataset'
	called on line 548 of file /usr/share/fish/completions/zfs.fish
from sourcing file /usr/share/fish/completions/zfs.fish

(Type 'help read' for related documentation)
```

**Comment by ammgws** [comment]
Huh, seems like this was coincidentally fixed in 85504ca694ae099f023ae0febb363238d9c64e8d but seems like that didn't make the cut for the 3.6.1 release.

**Comment by faho** [comment]
Closing this with a 3.6.2 milestone so we'd add it if we make a 3.6.2 release - other than that it's already fixed so the next full release will include it.

I do consider this to be a good reason to cut a 3.6.2 release, fwiw.

**Comment by bakhtiyarneyman** [comment]
Will there be a 3.6.2?

**Comment by broizter** [comment]
> Will there be a 3.6.2?

If you don't wanna wait for a release you can fix the bug by replacing the contents of /usr/share/fish/functions/__fish_is_zfs_feature_enabled.fish with this
```fish
function __fish_is_zfs_feature_enabled -a feature target -d "Returns 0 if the given ZFS feature is available or enabled>    type -q zpool
    or return
    set -l pool (string replace -r '/.*' '' -- $target)
    set -l feature_name ""
    if test -z "$pool"
        set feature_name (zpool get -H all 2>/dev/null | string match -r "\s$feature\s")
    else
        set feature_name (zpool get -H all $pool 2>/dev/null | string match -r "$pool\s$feature\s")
    end
    if test $status -ne 0 # No such feature
        return 1
    end
    set -l state (echo $feature_name | cut -f3)
    string match -qr '(active|enabled)' -- $state
    return $status
end
```

**Comment by bentolor** [comment]
@broizter I've adopted the patch mentioned above, but I still get on history search:


```
~  zfs create z0tank/games -o mountpoint=/home/ben/G/usr/share/fish/functions/__fish_is_zfs_feature_enabled.fish (line 8): Expected end of the statement, but found an incomplete token                                                                                                 So 30 Jul 2023 11:13:39 CEST
        set feature_name (zpool get -H all $pool 2>/dev/null | string match -r "$pool\s$feature\s")
                                                                                                 ^
from sourcing file /usr/share/fish/functions/__fish_is_zfs_feature_enabled.fish
	called on line 1 of file /usr/share/fish/completions/zfs.fish
from sourcing file /usr/share/fish/completions/zfs.fish
source: Error while reading file '/usr/share/fish/functions/__fish_is_zfs_feature_enabled.fish'
__fish_is_zfs_feature_enabled: Befehl nicht gefunden.
/usr/share/fish/completions/zfs.fish (line 344): 
if __fish_is_zfs_feature_enabled 'feature@bookmarks'
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file /usr/share/fish/completions/zfs.fish
__fish_is_zfs_feature_enabled: Befehl nicht gefunden.
/usr/share/fish/completions/zfs.fish (line 508): 
if __fish_is_zfs_feature_enabled 'feature@bookmarks'
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file /usr/share/fish/completions/zfs.fish
__fish_is_zfs_feature_enabled: Befehl nicht gefunden.
/usr/share/fish/completions/zfs.fish (line 548): 
if __fish_is_zfs_feature_enabled "feature@extensible_dataset"
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file /usr/share/fish/completions/zfs.fish
ame                                                      s                                                                                                                                                                                                                                ```

**Comment by TwoD** [comment]
Note that the comment above has a linewrap issue.
The first line should be exactly this:
```function __fish_is_zfs_feature_enabled -a feature target -d "Returns 0 if the given ZFS feature is available or enabled for the given full-path target (zpool or dataset), or any target if none given"```
and the second line begins with (indented) `set -l pool`

**Comment by bentolor** [comment]
Similar to @luispabon I get the same error after upstream update from PPA to 3.6.4.

Obviously I patched `/usr/share/fish/functions/__fish_is_zfs_feature_enabled.fish` manually before as described in the comments, but it seems to have been overwritten again with a broken version.

**Comment by bentolor** [comment]
@luispabon You're right: https://github.com/fish-shell/fish-shell/commit/85504ca694ae099f023ae0febb363238d9c64e8d is only in `master` while the last commit of 3.6.4 before release https://github.com/fish-shell/fish-shell/commit/b2ef44a277de5bfe85b193ae37c859ea61818ac6 is in [`Integration_3.6.4`](https://github.com/fish-shell/fish-shell/compare/Integration_3.6.4) and [`Integration_3.7.0`](https://github.com/fish-shell/fish-shell/compare/Integration_3.7.0).

It seems 3.6.x and 3.7.x are not including the fix yet. Not sure how the team cherry-picks/selects what goes into which integration branch.

**Comment by ammgws** [comment]
@zanchey FYI for next release

**Comment by zanchey** [comment]
2c460cd664a looks like it's in Integration_3.7.0, am I missing something?
